import { mutation } from "./_generated/server";

const EVANGELIUM_SECTIONS = [
  {
    section: "creed" as const,
    title: "The Creed — What Catholics Believe",
    content: `
<h2>The Meaning of Life</h2>
<p>Every human heart carries within it a restlessness that the things of this world cannot satisfy. St. Augustine of Hippo, writing from the depths of his own turbulent experience, captured this truth in one of the most celebrated lines in all of Christian literature: <strong>"You have made us for yourself, O Lord, and our heart is restless until it rests in Thee."</strong> This restlessness is not a defect or a disease; it is the very signature of our origin and our destiny. We were made by God and for God, and nothing less than God can fill the void within us.</p>
<p>The Catechism of the Catholic Church opens its very first chapter with this theme, affirming that "the desire for God is written in the human heart, because man is created by God and for God; and God never ceases to draw man to himself" (CCC 27). This desire manifests itself in humanity's universal reaching toward meaning, beauty, truth, and love — in art, in philosophy, in religion, and in the longings of ordinary daily life. Even those who have turned away from God often bear witness to this hunger in their sense of emptiness and dissatisfaction.</p>
<p>The Catholic tradition answers the question "What is the meaning of life?" with clarity and joy: man is made to know, love, and serve God in this life, and to be happy with Him forever in the next. The old Baltimore Catechism formulation remains profound: <strong>"God made me to know Him, to love Him, and to serve Him in this world, and to be happy with Him forever in heaven."</strong> This is not a life of grim duty but of flourishing — the full actualization of human potential in relationship with the living God. CCC 30 notes that only God, who created man in His image, "can fully reveal man to himself and bring him to the fullness of his truth."</p>
<p>The foundation of this teaching is the doctrine of the <strong>Imago Dei</strong> — that man is made in the image and likeness of God (Genesis 1:26-27). Unlike the rest of material creation, the human person is endowed with intellect and will, capacities that reflect the divine nature. This dignity is the basis of all human rights and the reason why every human life, from conception to natural death, is to be reverenced. Being made in God's image means that we are made for relationship — with God, with one another, and with the whole of creation — and that our ultimate happiness lies in the perfect fulfillment of this relational vocation.</p>

<h2>Creation and Fall</h2>
<p>The opening chapters of Genesis reveal two foundational truths: that the world is created by a good God and bears the imprint of His goodness, and that human beings, endowed with freedom, have chosen to reject the order God established. "In the beginning, God created the heavens and the earth" (Genesis 1:1). The six-day literary structure of Genesis 1 communicates theological truths: creation is ordered, beautiful, and good; the human person is its crown and culmination; and the rhythm of work and Sabbath rest belongs to the very fabric of reality. God surveys His creation and declares it "very good" (Genesis 1:31).</p>
<p>Man and woman are created last and in God's own image (Genesis 1:26-27), appointed as stewards of creation (Genesis 1:28). In Genesis 2, the more intimate narrative shows God forming man from the dust of the ground and breathing into his nostrils the breath of life — a powerful image of the intimacy between Creator and creature. The woman is drawn from the man's side, signifying their equality and complementarity. Adam and Eve in the garden represent the original state of <strong>original justice</strong>: harmony with God, with each other, with creation, and within themselves. They are free from suffering, ignorance, and death — gifts that flow from their relationship with God.</p>
<p>The account of the <strong>Fall</strong> in Genesis 3 narrates the catastrophic turning point of human history. Tempted by the serpent — identified by the Church with the devil — Eve and then Adam choose to disobey God's command, seeking to "be like God, knowing good and evil" (Genesis 3:5). This act of pride and disobedience ruptures their relationship with God. The consequences are immediate and devastating: shame, fear, blame, exile from the garden, and the introduction of suffering, toil, and death into human experience. The CCC identifies the four wounds of original sin: darkened intellect (<strong>ignorance</strong>), weakened will, disordered desires (<strong>concupiscence</strong>), and subjection to <strong>suffering and death</strong>.</p>
<p>Yet even in the midst of judgment, God speaks a word of hope. Genesis 3:15 contains the <strong>Proto-evangelium</strong> — the "first Gospel": "I will put enmity between you and the woman, and between your offspring and hers; he will strike your head, and you will strike his heel." This cryptic promise, directed at the serpent, is understood by the Church as the first announcement of the Messiah, who would come from the woman and would crush the power of evil. The whole of salvation history unfolds from this moment as God's patient, merciful, and relentless pursuit of His wayward children.</p>
<p>Original sin is not simply a story about Adam and Eve; it is the condition in which every human being is born (CCC 404). We do not inherit the personal guilt of Adam's act, but we do inherit its consequences: a human nature wounded by the loss of original justice, inclined toward sin, and subject to death. This is why every human being needs redemption — not merely moral instruction or self-improvement, but a genuine healing and restoration that only God can accomplish.</p>

<h2>Salvation History</h2>
<p>Salvation history is the story of God's faithful and progressive plan to restore humanity after the Fall. It is not a desperate improvisation but the unfolding of a plan conceived in eternity, one that unfolds across centuries through a series of <strong>covenants</strong> — solemn, binding agreements between God and His people. Each covenant advances the divine promise while also revealing more fully the character and purposes of God. The entire Old Testament is a preparation for the coming of Christ, the one in whom all the promises find their fulfillment.</p>
<p>The key covenants of salvation history form a cumulative structure: the covenant with <strong>Adam</strong> (implicit in creation), renewed with <strong>Noah</strong> after the flood (universal covenant with all humanity, sealed by the rainbow — Genesis 9:8-17); then the covenant with <strong>Abraham</strong>, through whom God promised to make a great nation and to bless all the families of the earth (Genesis 12:1-3, 15:18). This Abrahamic covenant is ratified by the mysterious sacrifice of Genesis 15 and renewed through Isaac and Jacob. Next comes the <strong>Mosaic covenant</strong> at Sinai, where God establishes Israel as His own people, giving them the Torah (Law) as a guide for life in relationship with Him (Exodus 19-24). Finally, the <strong>Davidic covenant</strong> promises an eternal kingdom and an everlasting dynasty: "Your house and your kingdom shall endure forever before me; your throne shall be established forever" (2 Samuel 7:16). This promise points beyond any earthly king to the Son of David who would reign forever.</p>
<p>The <strong>prophets</strong> play a crucial role in this history. Men like Isaiah, Jeremiah, Ezekiel, Hosea, and Micah called Israel back to covenant faithfulness, interpreted the meaning of national disasters as divine discipline, and above all kept alive the hope of a coming Messiah and a new and everlasting covenant. Isaiah's Servant Songs (Isaiah 42, 49, 50, 52-53) describe a mysterious figure who would bear the sins of the people — passages the Church has always read as prophecies of Christ's atoning death. Jeremiah announces a <strong>New Covenant</strong> written on the hearts of the people (Jeremiah 31:31-34).</p>
<p>The full meaning of salvation history is illuminated by the theological method of <strong>typology</strong>. A type is a person, event, or institution in the Old Testament that genuinely prefigures and points toward its fulfillment in Christ and the Church. Adam is a type of Christ (Romans 5:14) — as Adam's one act brought death, Christ's one act brings life. The Passover lamb prefigures the Lamb of God who takes away the sin of the world (John 1:29). The manna in the desert prefigures the Eucharist (John 6:48-51). The Exodus prefigures Baptism (1 Corinthians 10:1-4). Typology does not diminish the historical reality of the Old Testament events; rather, it reveals their deeper divine intentionality. St. Augustine's dictum holds: "The New Testament is hidden in the Old; the Old is made manifest in the New."</p>
<p>St. Paul writes that Christ came "in the fullness of time" (Galatians 4:4) — the kairos, the right moment in history chosen by God. The centuries of preparation — the law, the prophets, the wisdom literature, the experience of exile and return — had prepared a people, and indeed the whole Mediterranean world, for the coming of the Savior. The Jewish people, through their monotheism, their scriptures, and their messianic hope, served as the womb of salvation. The Greek language and philosophical culture provided a vocabulary for theological expression. The Roman Empire provided peace, roads, and a universal legal framework for the spread of the Gospel. All of history was converging on the moment when the Word became flesh.</p>

<h2>The Incarnation</h2>
<p><strong>"And the Word became flesh and dwelt among us"</strong> (John 1:14). These words from the Prologue of St. John's Gospel stand as one of the most astonishing sentences ever written — the announcement that the eternal Son of God, through whom all things were made, entered into the fabric of human history as one of us. The Incarnation is not a metaphor or a myth; it is the central claim of Christianity: that God became man in the person of Jesus Christ. This event changed everything. As St. Athanasius famously wrote, "God became man so that man might become God" — meaning, that through the Incarnation, we are offered a share in the divine life.</p>
<p>The Church uses the technical term <strong>hypostatic union</strong> to describe the mystery of Christ's person: He is one divine Person (the eternal Son, the Second Person of the Trinity) who possesses two complete natures — one divine and one fully human. This definition was solemnly proclaimed at the <strong>Council of Chalcedon</strong> (451 AD), which affirmed that Christ's two natures exist "without confusion, without change, without division, without separation." He is not half-God and half-man, nor a human person adopted by God. He is the eternal Son who took on a complete human nature — body, soul, intellect, and will — while remaining fully divine. This mystery is beyond full comprehension but is the key to understanding how Christ can be both our Savior and our example.</p>
<p>Central to the Incarnation is the role of the <strong>Virgin Mary</strong>. The Council of Ephesus (431 AD) declared Mary to be <strong>Theotokos</strong> — the "God-bearer" or "Mother of God." This title is not primarily about Mary's glory but about the identity of her Son: the one she carried in her womb and gave birth to in Bethlehem was truly God incarnate. The Annunciation (Luke 1:26-38) is the hinge moment: the angel Gabriel greets Mary with extraordinary news, and she responds with her free and total "Yes" — the Fiat: "Let it be done to me according to your word." In saying yes, Mary undoes the "no" of Eve. She is the New Eve, the mother of all the living in the order of grace, just as the first Eve was called mother of all in the order of nature.</p>
<p>The CCC identifies four principal reasons for the Incarnation (CCC 457-460): <strong>(1)</strong> "The Word became flesh to save us by reconciling us with God" — to take on our sin and offer the perfect sacrifice of atonement; <strong>(2)</strong> "so that thus we might know God's love" — in the face of Jesus we see most clearly how much God loves us (John 3:16); <strong>(3)</strong> "to be our model of holiness" — Jesus in His humanity shows us what it looks like to live a fully human life in complete openness to God; <strong>(4)</strong> "to make us partakers of the divine nature" (2 Peter 1:4) — the ultimate goal is <em>theosis</em>, our divinization, a genuine sharing in God's own life. The Incarnation is therefore not merely a rescue operation; it is the beginning of a transformation that reaches its completion in our union with God in heaven.</p>

<h2>The Life of Christ</h2>
<p>The earthly life of Jesus Christ is the fullest revelation of both God and man. Every event of His life — from the manger in Bethlehem to the empty tomb — is charged with saving significance. He was born in <strong>Bethlehem of Judea</strong>, in fulfillment of Micah's prophecy (Micah 5:2), during the reign of Caesar Augustus. The circumstances of His birth were humble: there was no room in the inn, and He was laid in a manger (Luke 2:7). Yet the angels announced His birth with cosmic joy, shepherds hastened to worship Him, and wise men from the East followed a star to present their gifts — recognizing in this child a king and a mystery beyond all human expectation. The presentation in the Temple (Luke 2:22-38) and the visit of the Magi (Matthew 2:1-12) each draw out different dimensions of His identity and mission.</p>
<p>The <strong>hidden years</strong> in Nazareth — from the return from Egypt to the beginning of His public ministry — represent the vast majority of Christ's earthly life. He lived as a craftsman in an obscure village, subject to His parents, growing "in wisdom and in stature and in favor with God and man" (Luke 2:52). This long period of hiddenness sanctifies the ordinary rhythms of human work, family life, and growth. The one recorded incident from this period — the Finding in the Temple (Luke 2:41-52) — offers a glimpse of His unique relationship with His heavenly Father: "Did you not know that I must be in my Father's house?" These hidden years were not wasted years; they were years of preparation and of the sanctification of human ordinariness.</p>
<p>Christ's <strong>public ministry</strong> began with His <strong>Baptism</strong> by John in the Jordan (Matthew 3:13-17), where the heavens opened, the Spirit descended like a dove, and the Father's voice declared: "This is my beloved Son, with whom I am well pleased." Immediately after, He was led into the desert for forty days of fasting and <strong>temptation</strong> by the devil (Matthew 4:1-11). His threefold rejection of Satan's temptations — for bread, for power, for spectacle — undoes the threefold failure of Israel in the desert and of Adam in the garden. He then began proclaiming, "Repent, for the kingdom of heaven is at hand" (Matthew 4:17), calling disciples, performing miracles of healing and exorcism, raising the dead, and teaching with an authority no prophet before Him had claimed.</p>
<p>The <strong>Sermon on the Mount</strong> (Matthew 5-7) is the Magna Carta of the Kingdom of God — the fullest expression of the new law that Christ came to establish. He does not abolish the old law but fulfills and perfects it: "You have heard it said... but I say to you." The Beatitudes open the Sermon, announcing a radical reversal of worldly values: the poor in spirit, the mourning, the meek, and the persecuted are called blessed, for the Kingdom belongs to them. The <strong>Transfiguration</strong> (Matthew 17:1-8) offers a momentary unveiling of Christ's divine glory on Mount Tabor — Peter, James, and John see Him radiant as the sun, conversing with Moses and Elijah, and hear again the Father's voice of affirmation. This event foreshadows the Resurrection and sustains the disciples through the coming darkness of the Passion.</p>

<h2>The Paschal Mystery</h2>
<p>The <strong>Paschal Mystery</strong> — the Passion, Death, Resurrection, and Ascension of Jesus Christ — is the very heart of the Christian faith. Everything before it was preparation; everything after it is consequence. St. Paul states it with uncompromising clarity: "If Christ has not been raised, your faith is futile and you are still in your sins" (1 Corinthians 15:17). The CCC calls the Paschal Mystery "the central mystery of the Christian faith and life" (CCC 571). It is not merely a historical event of the past but a saving reality that the Church makes present in every celebration of the Eucharist and the other sacraments.</p>
<p>The events of <strong>Holy Week</strong> unfold with dramatic intensity. On <strong>Palm Sunday</strong>, Jesus enters Jerusalem riding a donkey, acclaimed by the crowds — a fulfillment of Zechariah 9:9. The crowds cry "Hosanna to the Son of David!" but within days their mood will turn to "Crucify him!" At the <strong>Last Supper</strong> on Holy Thursday, Jesus institutes the Eucharist: taking bread and wine, He declares them to be His Body and Blood, given and poured out for many, and commands His disciples: "Do this in memory of me" (Luke 22:19). He then goes to the Garden of <strong>Gethsemane</strong>, where He prays in agony: "Father, if you are willing, remove this cup from me; nevertheless, not my will, but yours, be done" (Luke 22:42). He is then betrayed by Judas with a kiss, arrested, and abandoned by His disciples.</p>
<p>The trials before Caiaphas and Pilate are a grotesque inversion of justice — the Judge of all is judged by those He has made. He is scourged, crowned with thorns, mocked, and condemned to death. He carries His cross to <strong>Calvary</strong> and is crucified between two criminals. From the cross He speaks seven last words — of forgiveness, of promise, of abandonment, of thirst, of fulfillment: <strong>"It is finished"</strong> (John 19:30). He commends His spirit to the Father and dies. The veil of the Temple tears in two, signifying the end of the old covenant order and the opening of direct access to God. He is buried in a new tomb before the Sabbath begins.</p>
<p>On the <strong>third day</strong>, the tomb is found empty. The Risen Christ appears first to Mary Magdalene, then to the disciples on the road to Emmaus, then to the Eleven (John 20, Luke 24). His resurrection body is real and physical — the same body that was crucified, bearing the marks of the nails — yet transformed and glorified, no longer subject to the ordinary limitations of earthly existence. St. Paul presents the Resurrection as the foundation of Christian hope and the pledge of our own resurrection: "For as in Adam all die, so also in Christ shall all be made alive" (1 Corinthians 15:22; cf. 1 Corinthians 15:3-4). Forty days later, Christ <strong>ascends</strong> to the Father (Acts 1:9-11), taking His glorified humanity into the very life of the Trinity and opening heaven to us. Ten days after that, on <strong>Pentecost</strong>, the Holy Spirit descends upon the disciples gathered in the Upper Room — the promised Advocate who will guide the Church into all truth and empower the proclamation of the Gospel to the ends of the earth.</p>

<h2>The Trinity</h2>
<p>The doctrine of the <strong>Most Holy Trinity</strong> is the central mystery of Christian faith and life — "the mystery of God in himself" (CCC 234). It is not a philosophical puzzle invented by theologians but the very content of divine revelation: God has disclosed that He is not a solitary monad but a communion of three co-equal, co-eternal Persons — <strong>Father, Son, and Holy Spirit</strong> — sharing one divine nature. This mystery surpasses human reason; we could not have discovered it on our own. We know it only because God has revealed it, supremely in the person of Jesus Christ. As CCC 237 notes: "The mystery of the Trinity is the central mystery of the Christian faith and life. It is the mystery of God in himself."</p>
<p>The Old Testament contains <strong>hints and intimations</strong> of the Trinity — the plural "Let us make man in our image" (Genesis 1:26), the three visitors to Abraham (Genesis 18), the Spirit hovering over the waters of creation (Genesis 1:2), the Wisdom literature's personification of divine Wisdom — but the full revelation awaits the New Testament. At the <strong>Baptism of Jesus</strong>, all three Persons are simultaneously revealed: the Son is baptized, the Spirit descends as a dove, and the Father speaks from heaven (Matthew 3:16-17). The <strong>Great Commission</strong> explicitly names all three: "Baptizing them in the name of the Father and of the Son and of the Holy Spirit" (Matthew 28:19). The farewell discourse in John's Gospel (chapters 14-17) contains the richest Trinitarian teaching of Scripture, with the Son promising to send the Spirit from the Father.</p>
<p>Theologians distinguish the <strong>immanent Trinity</strong> (God as He is in Himself, in the eternal relations of the Persons) from the <strong>economic Trinity</strong> (God as He acts in history for our salvation). The immanent Trinity holds that the Father <em>begets</em> the Son eternally (not in time), and the Holy Spirit <em>proceeds</em> from the Father and the Son (the Western tradition, <em>Filioque</em>) or from the Father through the Son (Eastern tradition). These eternal relations constitute the distinct identities of the Persons: the Father is unbegotten; the Son is eternally begotten of the Father; the Holy Spirit proceeds from the Father and the Son. Yet all three share identically one divine essence, power, and will. The axiom holds: "The works of the Trinity <em>ad extra</em> are undivided" — all three Persons act together in every divine action toward creation.</p>
<p>The doctrine of the Trinity has profound practical implications for Christian life. <strong>Prayer</strong> is essentially Trinitarian: we pray <em>to</em> the Father, <em>through</em> the Son, <em>in</em> the Holy Spirit. The Sign of the Cross invokes all three Persons. <strong>Baptism</strong> initiates us into the life of the Trinity (Matthew 28:19). The Christian life is a participation in the divine communio — the perfect self-giving love of Father, Son, and Spirit. The Trinity is the model for human community: just as the Persons are distinct yet one, so human beings are called to a unity that respects and celebrates differences. The whole of Christian spirituality can be understood as a journey deeper into the mystery of Trinitarian love.</p>

<h2>The Church</h2>
<p>The Catholic Church is not a human organization that developed around the memory of Jesus; it is a divine institution founded by Christ Himself during His earthly ministry. The decisive moment of its foundation is recorded in Matthew 16:18-19, where Jesus, responding to Peter's confession of faith — "You are the Christ, the Son of the living God" — declares: <strong>"And I tell you, you are Peter, and on this rock I will build my Church, and the gates of hell shall not prevail against it. I will give you the keys of the kingdom of heaven."</strong> In giving Peter the keys, Christ grants him a unique authority of governance over the whole Church — an authority that is perpetuated in the ministry of his successors, the Bishops of Rome.</p>
<p>The Church is described by a rich variety of images in Scripture and Tradition, each illuminating a different dimension of her nature. She is the <strong>Body of Christ</strong> (Ephesians 1:22-23; 1 Corinthians 12:12-27): Christ is the Head and the faithful are the members, united by the one Spirit and called to work together as an organic whole. She is the <strong>Temple of the Holy Spirit</strong> (1 Corinthians 3:16-17): the Spirit dwells in the Church as God dwelt in the Jerusalem Temple, making her holy and guiding her into all truth (John 16:13). She is the <strong>Bride of Christ</strong> (Ephesians 5:25-27; Revelation 21:2): Christ loves the Church as a husband loves his wife, giving Himself up for her that she might be holy and without blemish. She is the <strong>People of God</strong>, a pilgrim people on their way to the heavenly homeland.</p>
<p>The Church bears <strong>four marks</strong> that identify her as the Church Christ founded. She is <strong>One</strong>: possessing one faith, one baptism, one set of sacraments, united under one head (CCC 813-822). She is <strong>Holy</strong>: made holy by the indwelling Spirit, even though her members are sinners; her sacraments are efficacious instruments of sanctification (CCC 823-829). She is <strong>Catholic</strong>: meaning universal, embracing all peoples, cultures, and times, possessing the fullness of the means of salvation (CCC 830-856). She is <strong>Apostolic</strong>: built on the foundation of the Apostles, maintaining unbroken continuity with the apostolic faith through the succession of bishops (CCC 857-865). These marks are not merely organizational attributes but gifts of the Holy Spirit.</p>
<p>The <strong>hierarchical structure</strong> of the Church reflects the order Christ established. The <strong>Pope</strong>, as Bishop of Rome and successor of Peter, exercises the fullness of episcopal power over the universal Church. The college of <strong>bishops</strong>, in communion with the Pope, share in the responsibility of governing and teaching the Church. <strong>Priests</strong> share in the ministry of bishops through ordination, serving the faithful in parishes and other apostolates. <strong>Deacons</strong> serve at the altar, the Word, and charity. The <strong>laity</strong> share in Christ's priestly, prophetic, and royal mission through Baptism and are called to transform the temporal order according to the Gospel. <strong>Mary</strong> stands as both the model and mother of the Church: model in her perfect faith and obedience, mother in her continuing intercession and spiritual maternity toward all the faithful (LG 63-65).</p>

<h2>Scripture and Tradition</h2>
<p>The Catholic Church holds that God has communicated His saving truth to humanity through two inseparable and mutually illuminating modes: <strong>Sacred Scripture</strong> and <strong>Sacred Tradition</strong>. Together they form one sacred deposit of the Word of God, entrusted to the Church and authentically interpreted by the <strong>Magisterium</strong> (the teaching authority of the Church, exercised by the Pope and bishops in communion with him). The Second Vatican Council's Dogmatic Constitution <em>Dei Verbum</em> (1965) provides the definitive modern statement of this doctrine, insisting that Scripture and Tradition "are bound together, flow from the same divine wellspring, and tend toward the same end" (DV 9).</p>
<p><strong>Sacred Scripture</strong> is the written word of God, composed under the inspiration of the Holy Spirit by human authors who, while using their own faculties and capacities, wrote only what God intended (CCC 106). The Catholic Bible contains <strong>73 books</strong> — 46 in the Old Testament and 27 in the New — including the deuterocanonical books (Tobit, Judith, 1-2 Maccabees, Wisdom, Sirach, Baruch) not found in the Protestant Old Testament. The Bible is inerrant in all that it affirms for the sake of our salvation (DV 11). Scripture must be read within the living Tradition of the Church, according to the analogy of faith, and with attention to the literary genres and historical contexts in which it was written.</p>
<p><strong>Sacred Tradition</strong> is the living transmission of the Gospel entrusted by Christ to the Apostles, handed on by them to their successors through the Holy Spirit. It includes not only the explicit teachings of the Apostles but also the Church's ongoing life of faith — her worship, her practice, her understanding deepened by the Holy Spirit over centuries (CCC 78). Tradition is not mere custom or human convention; it is the living memory of the Church. The creeds, the sacramental rites, the writings of the Fathers, the definitions of councils, and the sensus fidei of the faithful all belong to or witness to Tradition. Tradition preceded and shaped the New Testament — the Church recognized the canonical Scriptures under Tradition's guidance.</p>
<p>The Church reads Scripture according to <strong>four senses</strong>: (1) the <strong>literal sense</strong> — what the text directly states, the foundation of all other senses; (2) the <strong>allegorical sense</strong> — how the text points to Christ and the mysteries of faith (e.g., the crossing of the Red Sea signifying Baptism); (3) the <strong>moral sense</strong> — what the text teaches us about how to act rightly; (4) the <strong>anagogical sense</strong> — how the text points us toward our eternal destiny and the heavenly realities. The medieval rhyme captures it: "The letter teaches facts, allegory teaches what to believe, the moral teaches what to do, and the anagogy teaches what to hope for" (CCC 118). A full Catholic reading of Scripture integrates all four senses.</p>

<h2>Mary and the Four Last Things</h2>
<p>The Catholic Church honors the Virgin Mary with a veneration beyond that given to any other creature — a veneration called <em>hyperdulia</em>, distinguished from <em>latria</em> (worship due to God alone) and <em>dulia</em> (honor given to the saints). This honor is grounded in four solemn dogmatic definitions. First, the <strong>Divine Motherhood</strong> (Theotokos): defined at the Council of Ephesus (431 AD), this dogma affirms that Mary is truly the Mother of God because she is truly the mother of Jesus who is truly God. Second, the <strong>Perpetual Virginity</strong>: Mary was a virgin before, during, and after the birth of Christ. Third, the <strong>Immaculate Conception</strong>: defined by Pope Pius IX in 1854, this dogma affirms that Mary was preserved from original sin from the first moment of her conception, by a singular grace of God in anticipation of Christ's merits (CCC 491). Fourth, the <strong>Assumption</strong>: defined by Pope Pius XII in 1950, this affirms that at the end of her earthly life, Mary was taken up body and soul into heavenly glory (CCC 974).</p>
<p>Mary's role in salvation does not compete with Christ's unique mediatorship but flows from it. She is called <strong>Mediatrix</strong> because she cooperated uniquely in bringing the Mediator into the world and continues to intercede for the faithful. Some theologians use the title <strong>Co-redemptrix</strong> to signify her unique and subordinate cooperation in the work of redemption — not as an equal partner but as the one who, by her free consent at the Annunciation and her presence at the foot of the Cross, cooperated in a singular way with the redemptive sacrifice of her Son. These titles are not formally defined dogmas but represent an important strand of Catholic theological reflection on Mary's unique role.</p>
<p>The <strong>Four Last Things</strong> — Death, Judgment, Heaven, and Hell — are the ultimate realities that give urgency and meaning to the Christian life. <strong>Death</strong> is the end of earthly life, the moment when the soul separates from the body and the particular judgment occurs (CCC 1022). At the <strong>particular judgment</strong>, each soul immediately receives its eternal reward or punishment in accordance with its works and faith. Those who die in God's grace but still needing purification enter <strong>Purgatory</strong> — a state of purifying suffering, not a second chance, but a final cleansing that prepares the soul for the fullness of the beatific vision (CCC 1030-1032). The faithful on earth can assist the souls in Purgatory through prayer, fasting, and especially the offering of Mass.</p>
<p><strong>Heaven</strong> is the ultimate end and fulfillment of the deepest human longings — not a vague spiritual realm but the <strong>beatific vision</strong>: the direct, immediate, face-to-face knowledge and love of God (CCC 1023-1024). "We shall see him as he is" (1 John 3:2). This vision surpasses all that the natural mind can conceive; it is a participation in God's own knowledge of Himself, granted by the light of glory. In heaven, the redeemed enjoy perfect communion with the Trinity, with the angels, and with one another. <strong>Hell</strong> is the eternal state of those who die in mortal sin — not a punishment arbitrarily inflicted by God, but the definitive self-exclusion from God chosen by those who refused His love (CCC 1033-1037). The <strong>General Judgment</strong> at the end of time will manifest God's justice before all, and the resurrection of the body will reunite souls with their glorified bodies for eternity. The resurrection of the body asserts that our physicality is not a prison but an essential dimension of personhood, destined for eternal glory.</p>
`,
  },
  {
    section: "sacraments" as const,
    title: "The Sacraments — Signs of Grace",
    content: `
<h2>Liturgy and the Sacraments</h2>
<p><strong>Liturgy</strong> is the public, official worship of the Church — the participation of the whole Body of Christ, Head and members, in the priestly work of Christ (CCC 1069-1070). The word comes from the Greek <em>leitourgia</em>, meaning "public work" or "service of the people." In Christian usage, it designates the participation of the People of God in the work of God Himself. The liturgy is not merely a human activity but a divine one: it is Christ Himself who acts in and through the liturgical celebrations of the Church, making present His saving mysteries. The Catechism insists that "the liturgy is the summit toward which the activity of the Church is directed; and it is the font from which all her power flows" (SC 10; CCC 1074).</p>
<p>A <strong>sacrament</strong> is defined classically as "an outward sign instituted by Christ to give grace" (CCC 1131). This deceptively simple definition contains immense theological depth. The <em>outward sign</em> consists of <strong>matter</strong> (the physical element: water, oil, bread and wine, etc.) and <strong>form</strong> (the words that specify the meaning of the action). Together, the matter and form constitute the <em>sacramental sign</em>. Every sacrament requires a valid <strong>minister</strong> (the person who administers the sacrament) and a valid <strong>recipient</strong> (the person who receives it, with the proper dispositions). The seven sacraments are not merely symbols or expressions of faith; they truly <em>cause</em> the grace they signify — they are instrumental causes of grace through which God acts.</p>
<p>The Church teaches that the sacraments work <em>ex opere operato</em> — literally, "from the work performed" (CCC 1128). This means that the efficacy of a sacrament does not depend on the holiness of the minister or the subjective faith of the recipient (though the recipient's disposition affects how fully they benefit). What matters is the valid performance of the sacramental act with the proper intention "to do what the Church does." This principle protects the objectivity of sacramental grace and prevents it from becoming dependent on the personal merit of fallible human beings. The priest who celebrates Mass in a state of mortal sin still truly confects the Eucharist; a baptism administered by a sinner is still a valid baptism.</p>
<p>The <strong>seven sacraments</strong> span the whole of Christian life, accompanying it from beginning to end. They fall into three categories: the <strong>sacraments of initiation</strong> — Baptism (the door to the sacramental life), Confirmation (the strengthening of the Spirit), and Eucharist (the food of eternal life); the <strong>sacraments of healing</strong> — Penance (healing the soul wounded by sin) and Anointing of the Sick (healing body and soul in illness); and the <strong>sacraments of service</strong> — Holy Orders (for the service of the community) and Matrimony (for the service of the family and society). Three sacraments — Baptism, Confirmation, and Holy Orders — imprint an indelible spiritual <strong>character</strong> on the soul and can therefore never be repeated.</p>

<h2>Baptism and Confirmation</h2>
<p><strong>Baptism</strong> is the first and foundational sacrament, the "door" to the life of the Spirit and the gateway to all the other sacraments (CCC 1213). Jesus declared its necessity with absolute clarity: "Unless one is born of water and the Spirit, he cannot enter the kingdom of God" (John 3:5). He Himself was baptized by John in the Jordan, not because He needed cleansing from sin but to consecrate the waters for our sanctification and to reveal the Trinitarian mystery at the beginning of His public ministry. The Great Commission explicitly links Baptism to discipleship: "Go therefore and make disciples of all nations, baptizing them in the name of the Father and of the Son and of the Holy Spirit" (Matthew 28:19).</p>
<p>The <strong>effects of Baptism</strong> are comprehensive and transforming (CCC 1262-1274). Baptism forgives <em>all</em> sin — both original sin, which we inherit from Adam, and all actual personal sins committed before Baptism, together with all temporal punishment due to sin. The baptized person is reborn as a child of God, incorporated into the Body of Christ, made a member of the Church, and given a share in Christ's priestly, prophetic, and royal mission. The Holy Spirit takes up permanent residence in the soul. An indelible spiritual <strong>character</strong> is imprinted on the soul — marking one as belonging to Christ forever, which is why Baptism can never be repeated. The <strong>matter</strong> of Baptism is water (flowing water is preferred); the <strong>form</strong> is the explicit invocation of the Trinity: "I baptize you in the name of the Father, and of the Son, and of the Holy Spirit."</p>
<p>The Catholic Church baptizes <strong>infants</strong>, a practice attested from the earliest centuries of the Church (Origen, c. 185-254 AD, refers to it as received from the Apostles). Infant Baptism is theologically coherent because grace is a gift that does not await human merit or conscious decision; the faith of the parents and the Church is offered on behalf of the child, who will later make that faith personally their own. The Church also recognizes <strong>Baptism of desire</strong> (for catechumens who die before receiving the sacrament) and <strong>Baptism of blood</strong> (martyrdom for Christ).</p>
<p><strong>Confirmation</strong> completes and strengthens the grace of Baptism (CCC 1285-1314). If Baptism is spiritual birth, Confirmation is spiritual maturity — the moment when the baptized are more perfectly bound to the Church and endowed with a special strength of the Holy Spirit to spread and defend the faith. At the Last Supper, Christ promised the coming of the Spirit (John 14:16-17, 26); at Pentecost, the disciples received a powerful outpouring of that Spirit that transformed them from frightened men into courageous evangelists. Confirmation perpetuates this Pentecostal gift for each believer. The <strong>seven Gifts of the Holy Spirit</strong> — Wisdom, Understanding, Knowledge, Counsel, Fortitude, Piety, and Fear of the Lord (Isaiah 11:2-3) — are strengthened in Confirmation to equip the confirmed for mature Christian witness. The matter is the <strong>anointing with Sacred Chrism</strong> (oil mixed with balsam, consecrated by the bishop) on the forehead; the form is: "Be sealed with the Gift of the Holy Spirit." A <strong>sponsor</strong> presents the candidate, who ideally takes a saint's name, signifying a new mission in the Church.</p>

<h2>The Eucharist</h2>
<p>The <strong>Eucharist</strong> is the source and summit of the Christian life (Lumen Gentium 11; CCC 1324). Every other sacrament is ordered toward it; the entire life of the Church flows from it and returns to it. In the Eucharist, Christ is not merely remembered or symbolized — He is truly, really, and substantially present: His <strong>body, blood, soul, and divinity</strong> under the appearances of bread and wine. This is the doctrine of the <strong>Real Presence</strong>, affirmed by Scripture, proclaimed by the Church Fathers, and defined with precision by the Council of Trent. St. John Chrysostom (4th century) wrote: "It is not man who causes what is offered to become the Body and Blood of Christ, but Christ Himself." St. Ignatius of Antioch (d. c. 107 AD), just one generation after the Apostles, called the Eucharist "the medicine of immortality."</p>
<p>The word <strong>transubstantiation</strong> names the unique manner of Christ's presence in the Eucharist (CCC 1376). At the consecration, the entire <em>substance</em> of the bread and wine is converted into the substance of the Body and Blood of Christ, while only the <em>accidents</em> (the appearances — taste, color, texture, weight) of bread and wine remain. This is not a chemical transformation but a metaphysical one — a change of the deepest reality of the thing, worked by the power of God through the words of the priest acting <em>in persona Christi</em> (in the person of Christ). The doctrine is grounded in Christ's own words at the Last Supper: "This is my body... this is my blood" (Matthew 26:26-28), and in His teaching in the Bread of Life discourse: "For my flesh is true food, and my blood is true drink" (John 6:55).</p>
<p>The Mass is the <strong>re-presentation</strong> (not mere repetition) of the one sacrifice of Calvary (CCC 1367). Christ's sacrifice on the Cross was a once-for-all historical event (Hebrews 9:28); the Mass does not add to it or repeat it but makes it sacramentally present across time and space. The same Christ who offered Himself on Calvary offers Himself now through the ministry of the priest. Every Mass unites the worshipping community with the eternal sacrifice that lies at the center of history. This is why the Mass is not merely a communal meal or a religious ceremony; it is the most perfect act of worship possible for a human being. The institution of the Eucharist at the <strong>Last Supper</strong> (Holy Thursday) represents Christ's giving of Himself in advance of Calvary — the sacrifice is contained in the gift.</p>
<p>To receive the Eucharist fruitfully, the faithful must be in a <strong>state of grace</strong> — free from mortal sin. St. Paul warns severely: "Whoever eats the bread or drinks the cup of the Lord in an unworthy manner will be guilty of profaning the body and blood of the Lord" (1 Corinthians 11:27-29). Anyone who is conscious of mortal sin must first receive the sacrament of Penance. A <strong>one-hour fast</strong> from food and drink (except water and medicine) is required before reception. The spiritual fruits of worthy Communion are abundant: deeper union with Christ, nourishment of the soul, forgiveness of venial sins, preservation from future mortal sin, pledge of future glory, and strengthening of the bonds of ecclesial charity. <strong>Eucharistic adoration</strong> — the practice of praying before the Blessed Sacrament exposed in the monstrance — is a cherished Catholic devotion that prolongs the grace of the Mass into one's personal prayer life.</p>

<h2>Confession and Anointing</h2>
<p>The sacrament of <strong>Penance and Reconciliation</strong> (also called Confession or the sacrament of Conversion) is God's gift of forgiveness for sins committed after Baptism (CCC 1422-1498). On the evening of the Resurrection, the Risen Christ appeared to the Apostles and conferred upon them the power to forgive sins: "Receive the Holy Spirit. Whose sins you forgive are forgiven them, and whose sins you retain are retained" (John 20:22-23). This power — the "power of the keys" — is exercised by bishops and priests as ministers of the sacrament. The Church insists that God has willed this manner of reconciliation: it is not sufficient to confess one's sins privately to God alone; mortal sins must be confessed to a priest (CCC 1456).</p>
<p>The sacrament consists of three <strong>acts of the penitent</strong> and one act of the minister. The penitent must (1) make an <strong>examination of conscience</strong>, reviewing their sins since their last confession; (2) have <strong>contrition</strong> — sincere sorrow for sin. Contrition can be <em>perfect</em> (motivated by love of God above all else) or <em>imperfect</em> (motivated by fear of punishment, known as <em>attrition</em>). Both are sufficient for the sacrament, though perfect contrition alone (without the sacrament) forgives even mortal sin in cases of necessity, when accompanied by the desire to receive the sacrament; (3) have a <strong>firm purpose of amendment</strong> — the sincere intention to avoid sin and its near occasions in the future; and (4) make an integral <strong>confession</strong> of all mortal sins by species and number. The priest then imposes a <strong>penance</strong> (prayers or acts of reparation) and pronounces the <strong>absolution</strong>: "I absolve you from your sins in the name of the Father, and of the Son, and of the Holy Spirit." The Church strongly recommends the regular confession of venial sins as well, at least monthly.</p>
<p>The <strong>Anointing of the Sick</strong> continues the healing ministry of Christ (CCC 1499-1532). Jesus healed the sick throughout His public ministry as a sign of the coming of the Kingdom. He sent the Twelve to anoint the sick (Mark 6:13), and the Letter of James gives the explicit scriptural foundation for the sacrament: "Is anyone among you sick? He should summon the presbyters of the Church, and they should pray over him and anoint him with oil in the name of the Lord, and the prayer of faith will save the sick person, and the Lord will raise him up. If he has committed any sins, he will be forgiven" (James 5:14-15). The sacrament is intended not only for those at the point of death but for anyone suffering from serious illness, significant surgery, or the frailty of old age.</p>
<p>The <strong>effects</strong> of Anointing of the Sick are multiple: the strengthening, peace, and courage of the soul in its trial; the forgiveness of sins if the person is unable to confess; and sometimes the restoration of physical health, if it is beneficial for the person's salvation. The three sacraments given to those who are dying — Penance, Anointing, and the Eucharist received as <strong>Viaticum</strong> (food for the journey) — constitute the "last rites," the Church's final sacramental accompaniment for the soul on its passage from this life. Viaticum holds a special place among the sacraments for the dying: it is the body and blood of Christ, the pledge of resurrection and eternal life, given as provision for the last journey.</p>

<h2>Marriage and Holy Orders</h2>
<p>The sacrament of <strong>Matrimony</strong> elevates the natural institution of marriage between a baptized man and woman to the dignity of a sacrament (CCC 1601-1666). The Catholic Church insists that Christian marriage is a <strong>covenant</strong> — not merely a legal contract but a total, personal, irrevocable gift of self modeled on the covenant between Christ and His Church (Ephesians 5:25-32). This means that the marriage bond, once validly contracted and consummated, is permanent and indissoluble: "What God has joined, man must not separate" (Matthew 19:6). The two essential <strong>properties</strong> of marriage are <strong>unity</strong> (one husband and one wife) and <strong>indissolubility</strong> (the bond lasts until the death of one spouse). The Church's teaching on the indissolubility of marriage is not a harsh rule but a reflection of the nature of genuine love and its analogy with God's own faithful covenant love.</p>
<p>The spouses themselves are the ministers of the sacrament of Matrimony; they confer the sacrament upon each other through their free and public exchange of consent. The priest or deacon acts as the Church's official witness. The sacrament gives the couple special graces for their vocation: to love each other with the love of Christ, to be faithful in fidelity and hardship, and to welcome children generously as the fruit and sign of their conjugal love. The family that flows from marriage is called the <strong>domestic Church</strong> (<em>ecclesia domestica</em>) — a community of faith, hope, and charity that is the first school of Christian life for children. <strong>Annulments</strong> (declarations of nullity) do not dissolve a valid marriage; they are declarations that a valid sacramental marriage never existed in the first place, due to some defect in consent, capacity, or canonical form.</p>
<p>The sacrament of <strong>Holy Orders</strong> configures men to Christ the Priest, Prophet, and King, and empowers them to serve the Church in a ministerial capacity distinct from the common priesthood of all the baptized (CCC 1536-1600). The sacrament has <strong>three degrees</strong>: the <strong>episcopate</strong> (bishops), the <strong>presbyterate</strong> (priests), and the <strong>diaconate</strong> (deacons). Bishops possess the <em>fullness</em> of the sacrament of orders; they are the successors of the Apostles, responsible for the governance, sanctification, and teaching of their particular churches. Priests are co-workers of the bishops, sharing in their priestly ministry: they celebrate Mass, hear confessions, anoint the sick, witness marriages, and preach. Deacons serve the bishop and priests in the ministry of the Word, the altar, and charity.</p>
<p><strong>Apostolic succession</strong> is the unbroken chain of valid ordinations from the Apostles to the present day — an essential guarantee that the Church today stands in continuity with the Church founded by Christ. The matter of Holy Orders is the <em>laying on of hands</em> by the bishop; the form is the consecratory prayer. Like Baptism and Confirmation, Holy Orders imprints an <strong>indelible character</strong> on the soul and can never be repeated or undone. In the Latin Rite, candidates for priesthood make a vow of <strong>celibacy</strong>, choosing to consecrate their whole selves to God and His Kingdom in imitation of Christ's own celibate life. This is not a canonical requirement imposed from outside but a charism and sign of the eschatological Kingdom where "they neither marry nor are given in marriage" (Matthew 22:30). Permanent deacons may be married men.</p>
`,
  },
  {
    section: "morals" as const,
    title: "Christian Morals — Life in Christ",
    content: `
<h2>Virtues and Vices</h2>
<p>Christian morality is not primarily a set of rules to be observed but a life to be lived — the life of Christ in the Christian, animated by the Holy Spirit and oriented toward union with God. At the heart of Christian moral life is the concept of <strong>virtue</strong>: "a habitual and firm disposition to do good" (CCC 1803). Virtues are not merely good habits in the psychological sense; they are stable qualities of character that incline the will toward the good and make moral action easier, more consistent, and more joyful. The virtuous person does not merely do good acts occasionally; they have become, through practice and grace, the kind of person for whom goodness flows naturally. As Aristotle observed and Aquinas developed, virtue is the perfection of our human capacities in their proper order.</p>
<p>The <strong>Cardinal Virtues</strong> — so called because all other human virtues hinge upon them (<em>cardo</em> = hinge) — are the four primary moral virtues identified by classical philosophy and adopted by the Christian tradition (CCC 1805-1809):
<ul>
  <li><strong>Prudence</strong> (<em>Phronesis</em>) is "right reason in action" — the virtue that enables us to discern the true good in every circumstance and to choose the right means of achieving it. It is the "charioteer of the virtues," governing and directing all the others. The prudent person knows not merely what is good in the abstract but what to do here and now.</li>
  <li><strong>Justice</strong> is the constant and firm will to give to God and neighbor what is their due. It governs our relationships — with God (the virtue of religion), with other individuals (commutative justice), and with society (social and distributive justice). "Give to everyone what you owe them" (Romans 13:7).</li>
  <li><strong>Fortitude</strong> ensures firmness in difficulties and constancy in the pursuit of the good, even to the point of death. It is the courage to resist temptation, to endure suffering for the sake of what is right, and to maintain one's moral integrity in the face of threats and persecution.</li>
  <li><strong>Temperance</strong> moderates the attraction of pleasure and provides balance in the use of created goods. It ensures the will's mastery over the instincts and keeps desires within the limits of what is honorable. Chastity, sobriety, and modesty are forms of temperance.</li>
</ul>
</p>
<p>The <strong>Theological Virtues</strong> — Faith, Hope, and Charity — are of an entirely higher order, having God Himself as their origin, motive, and object (CCC 1812-1829). They are infused directly by God into the soul at Baptism and cannot be acquired by human effort alone. <strong>Faith</strong> is the virtue by which we believe in God and believe all that He has revealed and that the Church proposes for our belief (CCC 1814). <strong>Hope</strong> is the virtue by which we desire and expect with confidence the kingdom of heaven and eternal life, placing our trust not in ourselves but in God's power and fidelity (CCC 1817-1821). <strong>Charity</strong> is the greatest of all virtues (1 Corinthians 13:13): the virtue by which we love God above all things for His own sake, and love our neighbor as ourselves for love of God (CCC 1822-1829). Charity "binds everything together in perfect harmony" (Colossians 3:14) and is the form of all virtues — it animates and orders them all toward God.</p>
<p>Opposed to the virtues are the <strong>Seven Deadly Sins</strong> (or Capital Sins), so called because they are the principal sources from which other sins flow (CCC 1866). They are: <strong>Pride</strong> (disordered self-love, the root of all sin — it led to the fall of Satan and the fall of man); <strong>Avarice</strong> (inordinate love of material goods); <strong>Envy</strong> (sadness at another's good, with a desire to deprive them of it); <strong>Wrath</strong> (inordinate anger, desire for revenge); <strong>Sloth</strong> (spiritual laziness, sadness at the divine good); <strong>Gluttony</strong> (inordinate desire for food and drink); and <strong>Lust</strong> (inordinate desire for sexual pleasure). Each deadly sin has an opposing virtue: humility against pride, generosity against avarice, kindness against envy, meekness against wrath, diligence against sloth, temperance against gluttony, and chastity against lust. The spiritual life involves the deliberate practice of virtue and the disciplined struggle against vice.</p>

<h2>Natural Law and the Ten Commandments</h2>
<p>The <strong>natural law</strong> is God's eternal law as it is inscribed in the rational nature of every human being and discernible by reason alone (CCC 1954-1960). Because God is the Creator of human nature and of reason itself, His moral order is not alien to us but is written into our very constitution. St. Paul notes that even the Gentiles, who did not have the written Torah, "show that what the law requires is written on their hearts, while their conscience also bears witness" (Romans 2:15). Natural law is the basis of universal human rights and the foundation of all just civil law. Because it is rational, it is in principle accessible to all people of goodwill regardless of religious belief — which is why the Catholic Church engages in dialogue about moral questions in the public square on the basis of reason, not merely faith.</p>
<p>The primary precept of the natural law is: <em>Do good and avoid evil</em>. From this, other fundamental moral truths follow: preserve human life, pursue truth, live in community, worship the divine — obligations that recur across cultures and civilizations, even if they are applied differently. Natural law is universal (it applies to all people), immutable (it does not change across time or culture), and inviolable (no human law or authority can legitimately override it). The CCC notes that the natural law "provides the indispensable moral foundation for building the human community" (CCC 1959).</p>
<p>The <strong>Ten Commandments</strong> (Exodus 20:1-17; Deuteronomy 5:6-21) represent God's privileged expression and confirmation of the natural law, given in a specific historical context to form the people of Israel but addressed in their moral content to all humanity (CCC 2056-2082). They fall into two <strong>tables</strong>: the First Table (Commandments 1-3) governs our duties to God, and the Second Table (Commandments 4-10) governs our duties to one another:
<ol>
  <li><strong>You shall have no other gods before Me</strong> — the radical monotheism that orders all of life to the one true God; prohibits idolatry, superstition, and false worship.</li>
  <li><strong>You shall not take the name of the Lord your God in vain</strong> — reverence for God's name; prohibits blasphemy, false oaths, and irreverence.</li>
  <li><strong>Remember the Sabbath day, to keep it holy</strong> — fulfilled in the Christian Sunday, the Lord's Day; Mass attendance and rest from servile work.</li>
  <li><strong>Honor your father and your mother</strong> — the foundation of social order; duties of children to parents and of citizens to legitimate authority.</li>
  <li><strong>You shall not murder</strong> — the inviolable dignity of human life from conception to natural death; prohibits abortion, euthanasia, suicide, and unjust killing.</li>
  <li><strong>You shall not commit adultery</strong> — the sanctity of marriage and sexual integrity; prohibits all sexual acts outside of marriage.</li>
  <li><strong>You shall not steal</strong> — respect for others' property and the universal destination of goods.</li>
  <li><strong>You shall not bear false witness</strong> — the obligation of truth; prohibits lying, perjury, and calumny.</li>
  <li><strong>You shall not covet your neighbor's wife</strong> — purity of heart and thought regarding others' spouses.</li>
  <li><strong>You shall not covet your neighbor's goods</strong> — interior detachment from material things; prohibits envy and greed.</li>
</ol>
</p>
<p>Christ does not abolish the Commandments but <strong>fulfills and deepens</strong> them (Matthew 5:17). The Sermon on the Mount shows how the new law of the Gospel goes beyond external observance to the transformation of the heart: "You have heard it said, 'You shall not murder'... but I say to you that everyone who is angry with his brother will be liable to judgment" (Matthew 5:21-22). The Commandments set a moral minimum; the Beatitudes and the commandment to love describe the fullness toward which Christ calls His disciples. The new law is not a heavier burden but a higher freedom — the freedom of the children of God who act not from fear of punishment but from love.</p>

<h2>Grace and the Beatitudes</h2>
<p><strong>Grace</strong> is the free and undeserved gift by which God shares His own life with us (CCC 1996-2000). It is not merely God's external help or approval; it is a genuine participation in the divine nature (2 Peter 1:4), an ontological transformation of the human person. Without grace, we cannot begin, continue, or persevere in the moral and spiritual life. The entire Christian life is a life of grace — received, nurtured, and deepened through the sacraments, prayer, and the practice of virtue. As St. Augustine declares: "Our whole achievement is God's gift."</p>
<p>Theologians distinguish several dimensions of grace. <strong>Sanctifying grace</strong> (or habitual grace) is the stable and permanent gift that makes us children of God, heirs of heaven, and temples of the Holy Spirit — it is the "life of the soul" analogous to the natural life of the body. When mortal sin is committed, sanctifying grace is lost; it is restored through the sacrament of Penance. <strong>Actual grace</strong> refers to God's specific interventions — His enlightenments and movements of the will — that assist us in particular moral and spiritual acts. <strong>Sacramental grace</strong> is the specific grace proper to each of the seven sacraments, tailored to the particular needs and mission of each. All grace is given through the merits of Christ and distributed through the mediation of the Holy Spirit and the Church.</p>
<p>The <strong>Beatitudes</strong> (Matthew 5:3-12) are the heart of Christ's moral teaching — eight proclamations of blessedness that describe the character of those who enter the Kingdom of God (CCC 1716-1729). They do not describe worldly success but a radical reversal of values rooted in the life of Christ Himself. Each Beatitude names a form of poverty or vulnerability and declares it blessed — not because suffering is good in itself but because those who are detached from the false goods of this world are open to the true good of the Kingdom:
<ul>
  <li><strong>"Blessed are the poor in spirit"</strong> — those who acknowledge their total dependence on God, who hold material and spiritual possessions with open hands. Theirs is the kingdom of heaven.</li>
  <li><strong>"Blessed are those who mourn"</strong> — those who grieve over sin and the suffering of others, who do not anesthetize themselves against the pain of the world. They shall be comforted.</li>
  <li><strong>"Blessed are the meek"</strong> — not the passive or the weak, but those who have power under control, who rule their own passions and do not impose themselves violently on others. They shall inherit the earth.</li>
  <li><strong>"Blessed are those who hunger and thirst for righteousness"</strong> — those whose deepest desire is for justice and for God's will to be done. They shall be satisfied.</li>
  <li><strong>"Blessed are the merciful"</strong> — those who extend to others the forgiveness and compassion they themselves need from God. They shall receive mercy.</li>
  <li><strong>"Blessed are the pure in heart"</strong> — those whose inner life is undivided, transparent to God, free from duplicity and self-deception. They shall see God.</li>
  <li><strong>"Blessed are the peacemakers"</strong> — those who actively seek reconciliation and justice, bringing the shalom of God into broken situations. They shall be called children of God.</li>
  <li><strong>"Blessed are those who are persecuted for righteousness' sake"</strong> — those who suffer for their faith and their moral integrity. Theirs is the kingdom of heaven.</li>
</ul>
</p>
<p>The Beatitudes are not merely moral ideals but descriptions of a graced transformation. They can only be lived in the power of the Holy Spirit, who pours into our hearts the love of God (Romans 5:5) and gradually conforms us to the image of Christ. The Beatitudes and the gifts of the Holy Spirit form an integrated vision: the virtues — both natural and theological — are the stable dispositions of character, the gifts of the Spirit are the movements of grace that carry us beyond what virtue alone can achieve, and the Beatitudes describe the characteristic dispositions and beatitudes of those in whom this transformation is being accomplished.</p>

<h2>Moral Action</h2>
<p>Catholic moral theology analyzes human acts according to <strong>three determinants</strong> that together determine whether an action is morally good or evil (CCC 1750-1761). These are: (1) the <strong>moral object</strong> — what is done, the act itself considered apart from subjective intention; (2) the <strong>intention</strong> — the subjective purpose for which the act is performed, the agent's end or aim; (3) the <strong>circumstances</strong> — the morally relevant features of the situation (who, what, where, when, how, with what effects). The tradition summarizes: "A good end does not justify an evil means." For an action to be morally good, all three sources must be good. If any one is evil, the act is morally deficient, even if the other two are good.</p>
<p>Some acts are <strong>intrinsically evil</strong> — evil by reason of their object, regardless of the intention and circumstances (CCC 1756). These are acts that are, by their very nature, incompatible with the dignity of the human person and can never be legitimately chosen: murder of the innocent, torture, slavery, contraception, abortion, blasphemy. No intention however noble, and no circumstances however dire, can transform an intrinsically evil act into a morally good one. This teaching is a safeguard against the utilitarian logic that justifies evil means for supposedly good ends — a logic that has been used to justify some of history's greatest atrocities.</p>
<p><strong>Conscience</strong> is the proximate norm of morality — the act by which a person applies moral principles to a particular situation and judges the morality of a concrete act (CCC 1778-1782). Conscience is not a faculty of mere feeling or personal preference; it is an act of practical reason. Because it can err through ignorance or failure, conscience must be <strong>formed</strong> through education, prayer, study of Scripture and Church teaching, and wise counsel. The CCC insists that one must always obey a certain conscience but also must always seek to form conscience correctly. Erroneous conscience can diminish moral responsibility, but it does not make a wrong act right.</p>
<p><strong>Mortal sin</strong> is sin that "destroys charity in the heart of man by a grave violation of God's law; it turns man away from God... by preferring an inferior good to him" (CCC 1855). For a sin to be mortal, three conditions must be simultaneously present: <strong>grave matter</strong> (the act is seriously wrong); <strong>full knowledge</strong> (the person knows it is seriously wrong); and <strong>deliberate consent</strong> (the person freely chooses to do it). Mortal sin severs the relationship of charity with God and results in the loss of sanctifying grace. Without repentance and absolution, it leads to eternal death. <strong>Venial sin</strong> weakens but does not destroy charity; it inclines one toward further sin and deserves temporal punishment but does not deprive the soul of divine friendship. Both types are forgiven through the sacrament of Penance; venial sins are also forgiven through acts of charity, the Lord's Prayer, and other penitential acts.</p>

<h2>Christian Life in the World</h2>
<p>The Catholic Church's <strong>social teaching</strong> applies the Gospel to the structures and institutions of human society. It is not a political program but a body of moral principles derived from human dignity, the nature of the common good, and the demands of justice and charity. The foundation of all social teaching is the <strong>dignity of the human person</strong>, made in the image of God and redeemed by Christ. Every social, economic, and political arrangement must be evaluated by whether it upholds or undermines this dignity. As Pope John Paul II wrote, "Man is the way of the Church" (<em>Redemptor Hominis</em> 14) — concern for human beings in their full truth is the criterion of all social engagement.</p>
<p>Several key principles structure Catholic social teaching. The principle of <strong>solidarity</strong> affirms that we are all genuinely responsible for one another — that the human family is one and that my brother's suffering is my concern (CCC 1939-1942). The principle of <strong>subsidiarity</strong> holds that decisions should be made at the lowest level of society capable of handling them — higher levels of authority should not usurp functions that can be performed well by individuals or smaller communities (CCC 1883-1885). The <strong>common good</strong> — the sum total of social conditions which allow groups and individuals to reach their fulfillment — is the goal of social life (CCC 1906). The <strong>preferential option for the poor</strong> requires that the needs of the most vulnerable members of society receive special consideration in social and economic arrangements (CCC 2448).</p>
<p>Pope John Paul II's encyclical <em>Laborem Exercens</em> (1981) develops the dignity of <strong>human work</strong>: work is not merely an economic necessity but a participation in God's creative activity and a means of self-realization and service to the community. Workers have rights: to a just wage, to safe conditions, to rest, to organize, to form families supported by their labor. The economic order must serve the human person, not the other way around. Both unregulated capitalism that reduces workers to instruments of profit and totalitarian collectivism that denies personal freedom are contrary to human dignity and the Gospel.</p>
<p>The <strong>family</strong> is the fundamental cell of social life — the first community of persons in which the human being learns to give and receive love, to develop virtues, and to relate to God and neighbor. The Church defends the family with particular urgency because it is simultaneously the most natural and the most fragile of human institutions. Christian families are called to be <em>domestic churches</em> — centers of prayer, evangelization, and witness to the culture of life and love. <strong>Care for creation</strong> is also part of the moral life: God entrusted the earth to human stewardship, not ownership, and the degradation of the natural environment is a moral issue touching justice for present and future generations (cf. Pope Francis, <em>Laudato Si'</em>). Catholics engage in political life not to impose their faith by force but to offer the wisdom of the natural law and the Gospel for the service of the common good.</p>
`,
  },
  {
    section: "prayer" as const,
    title: "Christian Prayer — Conversation with God",
    content: `
<h2>The Life of Prayer</h2>
<p>Prayer is the central act of the Christian life — the moment at which the human person turns toward God with full attention and desire. St. John Damascene's classic definition, cited in the Catechism, calls prayer <strong>"the raising of one's mind and heart to God"</strong> (CCC 2559). This definition is deceptively simple: prayer is not primarily an exercise of the lips or the intellect but a movement of the whole person — mind, heart, will, affection — toward the living God. It is, as the CCC puts it, "the living relationship of the children of God with their Father who is good beyond measure, with His Son Jesus Christ and with the Holy Spirit" (CCC 2565). Prayer is the breath of the soul; without it, the interior life withers and dies.</p>
<p>The tradition identifies <strong>three forms or expressions of prayer</strong>, corresponding to the movement from external to interior (CCC 2700-2724). <strong>Vocal prayer</strong> uses words — spoken or sung — to address God, and includes the great liturgical prayers of the Church as well as personal vocal prayer. Vocal prayer is not inferior; Christ Himself prayed aloud in the synagogue and at Gethsemane. <strong>Meditation</strong> is discursive mental prayer that engages thought, imagination, emotion, and desire in order to deepen our understanding of the truths of faith and our response to God. It is the careful "chewing" of the Word of God and the mysteries of Christ. <strong>Contemplation</strong> is the highest form of prayer: a simple, loving gaze on God that goes beyond words and concepts into direct communion. It is a pure gift of grace, toward which meditation is a preparation.</p>
<p>The CCC further identifies <strong>five forms of prayer</strong> according to their content (CCC 2626-2643). <strong>Blessing and adoration</strong> — exalting God for His greatness and acknowledging our creaturely dependence. <strong>Petition</strong> — asking God for what we need, especially the forgiveness of sin and the coming of His Kingdom. <strong>Intercession</strong> — praying for the needs of others, participating in Christ's own intercessory prayer. <strong>Thanksgiving</strong> — recognizing every good as a gift from God and responding with gratitude. <strong>Praise</strong> — glorifying God for who He is, without any consideration of what He does for us. The Mass is the fullest expression of all five forms simultaneously. The <strong>Liturgy of the Hours</strong> (<em>Breviary</em>) is the official prayer of the Church — psalms, canticles, Scripture readings, and hymns prayed at fixed hours throughout the day — sanctifying the whole day and uniting every Christian in the prayer of Christ, the Head.</p>
<p><strong>Obstacles to prayer</strong> are real and must be honestly faced. Distraction — the wandering of the mind during prayer — is almost universal; the response is not to force the mind back violently but to redirect the heart gently. Spiritual <strong>dryness</strong> (aridity) — periods when prayer feels empty and God seems absent — is a normal part of the spiritual life and a school of perseverance and pure faith. <strong>Acedia</strong> — a kind of spiritual sloth or discouragement that leads one to give up praying — is one of the great enemies of interior life. The remedy is perseverance, structure, and humble trust that God acts even when we do not feel it. <strong>Jesus is the supreme model of prayer</strong>: the Gospels show Him withdrawing regularly to pray (Luke 5:16), spending whole nights in prayer before important decisions (Luke 6:12), and teaching His disciples by word and example the necessity and manner of prayer.</p>

<h2>The Lord's Prayer</h2>
<p>The <strong>"Our Father"</strong> — the Lord's Prayer — is the prayer that Jesus Himself gave us when His disciples asked, "Lord, teach us to pray" (Luke 11:1). It appears in two versions: a longer liturgical form in Matthew 6:9-13 and a shorter form in Luke 11:2-4. Tertullian, the early Christian writer, called it "the summary of the whole Gospel," and this is no exaggeration: every dimension of Christian faith and life is contained in its seven petitions. The CCC devotes its entire final section — nearly a hundred paragraphs — to a detailed commentary on the Our Father (CCC 2759-2865). To pray the Our Father with understanding and devotion is to pray the whole of Christian theology in miniature.</p>
<p>The opening address, <strong>"Our Father who art in heaven,"</strong> is itself a revolution. To call God "Father" — <em>Abba</em>, the intimate address Jesus used — is to claim an intimacy with God that no religion before Christianity dared assert as a universal privilege. This is not the address of a subject to a distant king but of a child to a father who loves beyond measure. The word <strong>"Our"</strong> has a communal dimension: the Lord's Prayer is never purely private. We pray it as members of the Body of Christ, in solidarity with all the baptized, carrying one another's needs before the Father. "Who art in heaven" does not confine God to a geographical location but affirms His transcendence and majesty — He is infinitely beyond us and infinitely close.</p>
<p>The <strong>seven petitions</strong> fall into two groups: the first three concern the glory of God; the last four concern our needs as his children (CCC 2803):
<ol>
  <li><strong>"Hallowed be thy name"</strong> — a prayer that God's name be honored and glorified in us and through us; a desire that all creation recognize and adore the holiness of God. This is the fundamental posture of worship.</li>
  <li><strong>"Thy kingdom come"</strong> — an eschatological cry for the final establishment of God's reign; a prayer for the conversion of sinners, for justice, for the coming of Christ in glory. Every Mass is an anticipation of this kingdom.</li>
  <li><strong>"Thy will be done, on earth as it is in heaven"</strong> — a total surrender of our will to God's, asking for the grace to obey God as perfectly on earth as the angels obey Him in heaven. This petition is the echo of Christ's prayer in Gethsemane.</li>
  <li><strong>"Give us this day our daily bread"</strong> — a petition for our material needs (trusting God rather than anxiety), but also for the Bread of Life, the Eucharist, the daily nourishment of the soul. "Daily" (<em>epiousios</em>) may also be translated "supersubstantial" — pointing to the Eucharistic dimension.</li>
  <li><strong>"Forgive us our trespasses, as we forgive those who trespass against us"</strong> — the only petition with a condition attached: we ask for God's mercy in the same measure as we extend mercy to others. This is the hinge of the Our Father; refusing to forgive another is to close the channel of God's forgiveness to ourselves (Matthew 6:14-15).</li>
  <li><strong>"Lead us not into temptation"</strong> — a prayer for God's grace in the spiritual battle; asking that we not be overcome by temptation and that we have the strength to turn away from occasions of sin. God does not tempt us (James 1:13) but allows testing; we pray for His protection.</li>
  <li><strong>"But deliver us from evil"</strong> — liberation from the Evil One (the definite article in the Greek suggests a personal enemy, the devil) and from all the evils — moral, physical, spiritual — that threaten us. The Church adds the doxology: "For thine is the kingdom, the power, and the glory, forever and ever. Amen" — a fitting conclusion of praise.</li>
</ol>
</p>

<h2>Praying the Mass</h2>
<p>The Second Vatican Council's <em>Sacrosanctum Concilium</em> (1963) calls for the <strong>"full, conscious, and active participation"</strong> of all the faithful in the liturgy (SC 14). This participation is not primarily external activity but interior engagement: uniting one's mind and heart to the priestly prayer of Christ, entering into the sacred mysteries with understanding and devotion. The Mass is not a spectacle to be watched or a devotional exercise to be privately performed; it is an action in which every baptized person participates according to their proper role, joining Christ's perfect sacrifice to the Father.</p>
<p>The structure of the Mass falls into two great parts, preceded by the Introductory Rites and concluded by the Concluding Rites. The <strong>Introductory Rites</strong> prepare us for the sacred encounter: the <em>Sign of the Cross</em> (invoking the Trinity in whose life we participate), the <em>greeting</em> of the priest, the <em>Penitential Act</em> (acknowledging our unworthiness and asking for mercy), the <em>Gloria</em> (a hymn of praise sung on feast days and Sundays — a participation in the song of the angels), and the <em>Collect</em> (the opening prayer that gathers the intentions of all into one). Interiorly, we arrive at Mass shedding our preoccupations and opening ourselves to God.</p>
<p>The <strong>Liturgy of the Word</strong> is the first great movement of the Mass: God speaks, and we listen. It includes a First Reading (usually from the Old Testament), a Responsorial Psalm (the Church's song of meditation on God's Word), a Second Reading (from the epistles), the <em>Gospel Acclamation</em> (Alleluia), and the <strong>Gospel</strong> — the climax of the Liturgy of the Word, received standing and greeted with the Sign of the Cross on forehead, lips, and heart (may His Word be in my mind, on my lips, and in my heart). The <em>Homily</em> breaks open the Word for the community. The <em>Creed</em> is our response of faith. The <em>Prayer of the Faithful</em> is our intercession for the Church and the world — our priestly exercise of the baptismal priesthood.</p>
<p>The <strong>Liturgy of the Eucharist</strong> is the second and climactic movement. The <em>Offertory</em> brings forward bread, wine, and our lives to be offered. The <em>Eucharistic Prayer</em> — the great prayer of consecration — begins with the <em>Preface</em> (a soaring proclamation of God's saving deeds) and the <em>Sanctus</em> (Holy, Holy, Holy — our joining with the angels' eternal song). The <em>Consecration</em> is the moment of transformation: through the priest's words spoken in persona Christi, the bread and wine become the Body and Blood of Christ. The <em>Memorial Acclamation</em> is the assembly's response of faith ("We proclaim your death, O Lord, and profess your resurrection, until you come again"). The <em>Doxology</em> and the Great Amen conclude the Eucharistic Prayer — the Amen is our "Yes" to everything that has been offered. The <em>Communion Rite</em> — the Our Father, Sign of Peace, Agnus Dei, and reception of Communion — draws us into the most intimate possible union with Christ. The <em>Concluding Rites</em> send us forth: "Go and announce the Gospel of the Lord." We are dismissed not to return to ordinary life but to carry the Eucharist we have received into the world.</p>

<h2>The Practice of Confession</h2>
<p>The <strong>sacrament of Confession</strong> (Penance and Reconciliation) is one of the greatest gifts Christ has given His Church — the ongoing availability of God's mercy to sinners who have fallen after Baptism. Regular Confession is not merely a spiritual discipline for scrupulous personalities; it is the appointed means by which the Church offers healing to all who have wounded their relationship with God through sin. Pope John Paul II went to Confession every week; the saints of every era practiced frequent Confession as a cornerstone of their spiritual lives. The Church prescribes it at least once per year (specifically if one is conscious of mortal sin), but monthly Confession is warmly recommended for all who seek to grow in holiness.</p>
<p>A good Confession has five elements. First, the <strong>examination of conscience</strong>: a prayerful and honest review of one's sins since the last Confession, using the Ten Commandments and the precepts of the Church as a guide. This is not a legalistic counting of infractions but a sincere look at how one has loved or failed to love — God, neighbor, and self. The examination should cover thoughts, words, deeds, and omissions. Second, <strong>contrition</strong>: genuine sorrow for sin, not merely regret at consequences. Perfect contrition (sorrow because sin offends the God we love) is most pleasing to God; imperfect contrition (sorrow from fear of hell or other consequences) is also sufficient for a valid sacrament. Both must include a sincere desire to sin no more. Third, a <strong>firm purpose of amendment</strong>: the intention to avoid the sin and its near occasions in the future. This does not require certainty that one will never fall again — only a sincere resolve in the present moment.</p>
<p>Fourth, the <strong>confession of sins</strong> itself: telling one's mortal sins to the priest by kind (what type of sin) and number (approximately how many times). This integral confession is required by divine law (CCC 1456). Venial sins may also be confessed and receive specific absolution. The confession should be humble, honest, and complete — neither minimizing sins through vague generalities nor exaggerating them. One must not consciously withhold any known mortal sin, since doing so would invalidate the sacrament and add the sin of sacrilege. Fifth, the priest imposes a <strong>penance</strong> — prayers or acts of charity and reparation — and then pronounces the words of <strong>absolution</strong>: "I absolve you from your sins in the name of the Father, and of the Son, and of the Holy Spirit." These words, spoken by the priest as minister of the sacrament, truly and objectively forgive all sins confessed with proper dispositions.</p>
<p>The <strong>seal of Confession</strong> is absolute and inviolable. A priest may never, under any circumstances, directly or indirectly reveal what he has heard in Confession — not to protect a child at risk, not under legal compulsion, not under torture. This seal is a matter of natural and divine law, not merely Church discipline, and has been maintained by martyrs who preferred death to its violation. The absolute seal is not a protection for sinners against accountability; it is a protection of the sacred space of God's mercy, ensuring that no one will ever hesitate to confess their worst sins for fear of exposure. It is one of the most remarkable and admirable features of the Catholic sacramental system.</p>

<h2>Catholic Devotions</h2>
<p>Catholic <strong>devotions</strong> are forms of prayer and piety that, while not part of the official liturgy, are nourished by it and ordered toward it. They represent the flowering of the People of God's love — their desire to honor God, Our Lady, and the saints in ways that touch the heart and the senses as well as the intellect. The CCC notes that "the religious sense of the Christian people has always found expression in various forms of piety surrounding the Church's sacramental life, such as the veneration of relics, visits to sanctuaries, pilgrimages, processions, the stations of the cross, religious dances, the rosary, medals, etc." (CCC 1674). These devotions, when properly ordered to the liturgy, are warmly encouraged by the Church as means of sanctification.</p>
<p>The most beloved Catholic devotion is the <strong>Holy Rosary</strong>. Tradition associates its origin with St. Dominic (13th century), though it developed gradually over several centuries. Our Lady of Fatima (1917) specifically requested its daily recitation. The Rosary is a <strong>Scripture-based, Christocentric meditation</strong> that contemplates the mysteries of Christ's life in company with His mother. Its structure consists of the Apostles' Creed, one Our Father, three Hail Marys, and one Glory Be for intentions; then five decades, each consisting of an Our Father, ten Hail Marys, and a Glory Be, with a mystery of Christ's life announced and meditated upon during each decade. Pope John Paul II added the Luminous Mysteries in 2002. The <strong>four sets of mysteries</strong> are:
<ul>
  <li><strong>Joyful Mysteries</strong>: The Annunciation, the Visitation, the Nativity, the Presentation in the Temple, the Finding of Jesus in the Temple.</li>
  <li><strong>Luminous Mysteries</strong>: The Baptism of Jesus, the Wedding at Cana, the Proclamation of the Kingdom, the Transfiguration, the Institution of the Eucharist.</li>
  <li><strong>Sorrowful Mysteries</strong>: The Agony in the Garden, the Scourging at the Pillar, the Crowning with Thorns, the Carrying of the Cross, the Crucifixion and Death.</li>
  <li><strong>Glorious Mysteries</strong>: The Resurrection, the Ascension, the Descent of the Holy Spirit, the Assumption of Mary, the Coronation of Mary.</li>
</ul>
</p>
<p>The <strong>Stations of the Cross</strong> (Via Crucis) are a devotion in which the faithful walk with Christ through the fourteen traditional stations of His Passion and death: (1) Jesus is condemned to death; (2) Jesus takes up His cross; (3) Jesus falls the first time; (4) Jesus meets His mother; (5) Simon of Cyrene helps carry the cross; (6) Veronica wipes the face of Jesus; (7) Jesus falls the second time; (8) Jesus meets the women of Jerusalem; (9) Jesus falls the third time; (10) Jesus is stripped of His garments; (11) Jesus is nailed to the cross; (12) Jesus dies on the cross; (13) Jesus is taken down from the cross; (14) Jesus is laid in the tomb. Some forms add a fifteenth station: the Resurrection. Traditionally prayed on Fridays and especially during Lent, the Stations of the Cross unite us spiritually with Christ's atoning suffering and cultivate gratitude for His sacrifice.</p>
<p><strong>Eucharistic Adoration</strong> — the practice of praying before Jesus truly present in the Blessed Sacrament, whether reserved in the tabernacle or exposed in the monstrance — is one of the most powerful forms of Catholic prayer. Many great saints attributed their deepest conversions and the graces of their apostolic fruitfulness to time spent in adoration. St. Peter Julian Eymard said, "Holy Communion is the shortest and safest way to heaven." The <strong>Brown Scapular of Our Lady of Mount Carmel</strong>, a sacramental consisting of two small pieces of brown wool connected by strings and worn over the shoulders, is a sign of consecration to Mary and her promise of her protection and intercession. The <strong>Angelus</strong>, prayed three times daily at 6 a.m., noon, and 6 p.m., meditates on the Annunciation and asks for Mary's intercession. <strong>Novenas</strong> — nine days of prayer for a specific intention, imitating the nine days the Apostles prayed in the Upper Room between Ascension and Pentecost — are a classic form of petitionary prayer. <strong>Litanies</strong> — the Litany of Loreto, the Litany of the Sacred Heart, the Litany of the Saints — invoke God, Mary, and the saints in a rhythmic, prayerful series of invocations and responses. Together, these devotions build up the inner life of the Catholic and draw the whole person — body, senses, imagination, intellect, and will — into the great act of love that is the Christian life.</p>
`,
  },
];

export const seedEvangelium = mutation({
  args: {},
  handler: async (ctx) => {
    for (const s of EVANGELIUM_SECTIONS) {
      const existing = await ctx.db
        .query("evangelium")
        .withIndex("by_section", (q) => q.eq("section", s.section))
        .first();
      if (existing) {
        await ctx.db.patch(existing._id, {
          title: s.title,
          content: s.content,
          lastUpdated: new Date().toISOString(),
        });
      } else {
        await ctx.db.insert("evangelium", {
          section: s.section,
          title: s.title,
          content: s.content,
          lastUpdated: new Date().toISOString(),
        });
      }
    }
    return { updated: EVANGELIUM_SECTIONS.length };
  },
});
