import { mutation } from "./_generated/server";

// Saints from the Roman Liturgical Calendar (mycatholic.life)
// Only those likely missing from the main seed (which covers 1 per day)
// These are additional liturgical feast days for saints already celebrated on other days,
// or saints that may have been given placeholder names in the original seed.

function dayOfYear(month: number, day: number): number {
  const months = [0, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];
  let doy = day;
  for (let i = 1; i < month; i++) doy += months[i];
  return doy;
}

function buildBio(s: {
  name: string;
  feastDate: string;
  shortBio: string;
  patronOf?: string;
  bornYear?: string;
  diedYear?: string;
  tags: string[];
  feastType?: string;
  liturgicalColor?: string;
  canonizedBy?: string;
}): string {
  return `<p>${s.shortBio}</p>
<p>${s.name} is venerated on ${s.feastDate} in the Roman Liturgical Calendar${s.feastType ? ` as a ${s.feastType}` : ""}. ${s.liturgicalColor ? `The liturgical color for this feast is ${s.liturgicalColor}.` : ""}</p>
${s.patronOf ? `<p><strong>Patronage:</strong> ${s.patronOf}</p>` : ""}
${s.tags.length ? `<p><strong>Known for:</strong> ${s.tags.join(", ")}.</p>` : ""}
${s.canonizedBy ? `<p><strong>Canonized by:</strong> ${s.canonizedBy}</p>` : ""}`;
}

const ADDITIONAL_SAINTS = [
  {
    name: "Saint Basil the Great",
    month: 1, day: 2,
    feastDate: "January 2",
    feastType: "Memorial",
    liturgicalColor: "White",
    shortBio: "Bishop, Doctor of the Church, and defender of Nicene orthodoxy against Arianism. Co-founder of Eastern monasticism with his friend Saint Gregory Nazianzen.",
    bornYear: "c. 329",
    diedYear: "379",
    patronOf: "hospital administrators, reformers of monastic life",
    canonizedBy: "Pre-Congregation",
    tags: ["Doctor of the Church", "Bishop", "Monastic", "Eastern Church"],
  },
  {
    name: "Saint Gregory Nazianzen",
    month: 1, day: 2,
    feastDate: "January 2",
    feastType: "Memorial",
    liturgicalColor: "White",
    shortBio: "Archbishop of Constantinople and Doctor of the Church, called 'the Theologian' for his Five Theological Orations on the Trinity. A brilliant poet and defender of orthodox faith.",
    bornYear: "c. 329",
    diedYear: "c. 390",
    patronOf: "theologians, poets",
    canonizedBy: "Pre-Congregation",
    tags: ["Doctor of the Church", "Archbishop", "Theologian", "Eastern Church"],
  },
  {
    name: "Saint Elizabeth Ann Seton",
    month: 1, day: 4,
    feastDate: "January 4",
    feastType: "Memorial (USA)",
    liturgicalColor: "White",
    shortBio: "First native-born American to be canonized. Widowed mother of five, she converted to Catholicism and founded the Sisters of Charity, establishing the first Catholic school system in America.",
    bornYear: "1774",
    diedYear: "1821",
    patronOf: "Catholic schools, widows, people ridiculed for their faith",
    canonizedBy: "Pope Paul VI, 1975",
    tags: ["Convert", "Foundress", "Educator", "Mother", "American"],
  },
  {
    name: "Saint John Neumann",
    month: 1, day: 5,
    feastDate: "January 5",
    feastType: "Memorial (USA)",
    liturgicalColor: "White",
    shortBio: "Redemptorist bishop of Philadelphia and the first male American citizen to be canonized. He organized the first Catholic diocesan school system and is known for his pastoral zeal.",
    bornYear: "1811",
    diedYear: "1860",
    patronOf: "Catholic education, immigrants",
    canonizedBy: "Pope Paul VI, 1977",
    tags: ["Bishop", "Redemptorist", "Educator", "Immigrant", "American"],
  },
  {
    name: "Saint André Bessette",
    month: 1, day: 6,
    feastDate: "January 6",
    feastType: "Optional Memorial (USA)",
    liturgicalColor: "White",
    shortBio: "Holy Cross brother known as the 'Miracle Worker of Montreal.' He had deep devotion to Saint Joseph and is credited with thousands of miraculous healings. He built the famous Saint Joseph's Oratory in Montreal.",
    bornYear: "1845",
    diedYear: "1937",
    patronOf: "the sick, caregivers",
    canonizedBy: "Pope Benedict XVI, 2010",
    tags: ["Religious Brother", "Miracle Worker", "Devotion to St. Joseph", "Canadian"],
  },
  {
    name: "Saint Raymond of Penyafort",
    month: 1, day: 7,
    feastDate: "January 7",
    feastType: "Memorial",
    liturgicalColor: "White",
    shortBio: "Dominican priest, canonist, and confessor of Pope Gregory IX. He compiled the Decretals of Gregory IX, the first official codification of canon law, and encouraged Thomas Aquinas to write the Summa Contra Gentiles.",
    bornYear: "c. 1175",
    diedYear: "1275",
    patronOf: "canon lawyers, medical record librarians",
    canonizedBy: "Pope Clement VIII, 1601",
    tags: ["Dominican", "Canon Law", "Confessor", "Scholar"],
  },
  {
    name: "Saint Hilary of Poitiers",
    month: 1, day: 13,
    feastDate: "January 13",
    feastType: "Memorial",
    liturgicalColor: "White",
    shortBio: "Bishop of Poitiers and Doctor of the Church, called the 'Athanasius of the West' for his defense of the divinity of Christ against Arianism. His treatise De Trinitate is a masterwork of Christian theology.",
    bornYear: "c. 315",
    diedYear: "c. 368",
    patronOf: "lawyers, people with snake bites",
    canonizedBy: "Pre-Congregation; Doctor of the Church declared by Pope Pius IX, 1851",
    tags: ["Doctor of the Church", "Bishop", "Anti-Arian", "Theologian"],
  },
  {
    name: "Saint Anthony of the Desert",
    month: 1, day: 17,
    feastDate: "January 17",
    feastType: "Memorial",
    liturgicalColor: "White",
    shortBio: "The father of Christian monasticism. He withdrew into the Egyptian desert to pray, fast, and battle demons — his life, written by Saint Athanasius, inspired countless thousands to pursue the monastic life.",
    bornYear: "c. 251",
    diedYear: "356",
    patronOf: "monks, hermits, butchers, basket weavers, gravediggers, skin diseases",
    canonizedBy: "Pre-Congregation",
    tags: ["Monk", "Hermit", "Desert Father", "Monasticism"],
  },
  {
    name: "Saint Sebastian",
    month: 1, day: 20,
    feastDate: "January 20",
    feastType: "Memorial",
    liturgicalColor: "Red",
    shortBio: "Roman soldier and martyr under Emperor Diocletian. He was secretly a Christian who encouraged fellow Christians awaiting martyrdom. Shot with arrows and left for dead, he survived, but was later beaten to death.",
    bornYear: "c. 256",
    diedYear: "c. 288",
    patronOf: "athletes, soldiers, archers, plague victims, police officers",
    canonizedBy: "Pre-Congregation",
    tags: ["Martyr", "Soldier", "Roman", "Early Church"],
  },
  {
    name: "Saint Fabian",
    month: 1, day: 20,
    feastDate: "January 20",
    feastType: "Memorial",
    liturgicalColor: "Red",
    shortBio: "Pope and martyr who organized the Church in Rome into districts served by deacons and promoted the dignity of Christian burial. He was elected pope after a dove reportedly landed on his head during the election.",
    bornYear: "Unknown",
    diedYear: "250",
    patronOf: "popes",
    canonizedBy: "Pre-Congregation",
    tags: ["Pope", "Martyr", "Early Church", "Roman"],
  },
  {
    name: "Saint Agnes",
    month: 1, day: 21,
    feastDate: "January 21",
    feastType: "Memorial",
    liturgicalColor: "Red",
    shortBio: "A young Roman girl of about 13 who chose death over the loss of her virginity or apostasy. One of the most celebrated virgin-martyrs of the early Church, her name means 'lamb' in Latin.",
    bornYear: "c. 291",
    diedYear: "c. 304",
    patronOf: "girls, chastity, gardeners, the Children of Mary",
    canonizedBy: "Pre-Congregation",
    tags: ["Martyr", "Virgin", "Early Church", "Roman", "Youth"],
  },
  {
    name: "Saint Vincent of Saragossa",
    month: 1, day: 22,
    feastDate: "January 22",
    feastType: "Optional Memorial",
    liturgicalColor: "Red",
    shortBio: "Deacon of Saragossa, Spain, and the first martyr of the Iberian Peninsula. He endured horrific tortures under Dacian, governor of Spain, with extraordinary courage and cheerfulness.",
    bornYear: "Unknown",
    diedYear: "304",
    patronOf: "wine makers, vinegar makers, school children",
    canonizedBy: "Pre-Congregation",
    tags: ["Martyr", "Deacon", "Spanish", "Early Church"],
  },
  {
    name: "Saint Francis de Sales",
    month: 1, day: 24,
    feastDate: "January 24",
    feastType: "Memorial",
    liturgicalColor: "White",
    shortBio: "Bishop of Geneva and Doctor of the Church. His gentle, patient method of evangelization reconverted thousands from Calvinism. His Introduction to the Devout Life taught ordinary people how to live holy lives in the world.",
    bornYear: "1567",
    diedYear: "1622",
    patronOf: "journalists, writers, the deaf, the Catholic press",
    canonizedBy: "Pope Alexander VII, 1665; Doctor of the Church: Pope Pius IX, 1877",
    tags: ["Doctor of the Church", "Bishop", "Missionary", "Writer", "Spiritual Director"],
  },
  {
    name: "The Conversion of Saint Paul",
    month: 1, day: 25,
    feastDate: "January 25",
    feastType: "Feast",
    liturgicalColor: "White",
    shortBio: "The feast commemorating the moment Saul of Tarsus, a persecutor of Christians, was struck down on the road to Damascus and encountered the Risen Christ, becoming Paul the Apostle — the greatest missionary of the early Church.",
    bornYear: "c. 5 AD",
    diedYear: "c. 65 AD",
    patronOf: "missions, Gentile Christians",
    tags: ["Apostle", "Missionary", "Conversion", "Scripture"],
  },
  {
    name: "Saints Timothy and Titus",
    month: 1, day: 26,
    feastDate: "January 26",
    feastType: "Memorial",
    liturgicalColor: "White",
    shortBio: "Two of Saint Paul's closest companions and co-workers in the Gospel. Timothy was bishop of Ephesus; Titus was bishop of Crete. Paul addressed pastoral letters to each of them, now part of the New Testament.",
    bornYear: "1st century",
    diedYear: "1st century",
    patronOf: "stomach ailments (Timothy); Crete (Titus)",
    canonizedBy: "Pre-Congregation",
    tags: ["Bishop", "Apostolic Companion", "New Testament", "Early Church"],
  },
  {
    name: "Saint Angela Merici",
    month: 1, day: 27,
    feastDate: "January 27",
    feastType: "Optional Memorial",
    liturgicalColor: "White",
    shortBio: "Italian mystic and educator who founded the Company of Saint Ursula (Ursulines), the first religious teaching order of women in the Church, dedicated to educating girls and caring for the sick and needy.",
    bornYear: "1474",
    diedYear: "1540",
    patronOf: "disabled people, sick people, educators of girls",
    canonizedBy: "Pope Pius VII, 1807",
    tags: ["Foundress", "Educator", "Mystic", "Women Religious"],
  },
  {
    name: "Saint Thomas Aquinas",
    month: 1, day: 28,
    feastDate: "January 28",
    feastType: "Memorial",
    liturgicalColor: "White",
    shortBio: "Dominican friar, priest, and the preeminent theologian and philosopher of the Catholic tradition. Called the 'Angelic Doctor,' his Summa Theologica remains the greatest systematic work of Catholic theology.",
    bornYear: "c. 1225",
    diedYear: "1274",
    patronOf: "students, schools, theologians, academics, pencil makers",
    canonizedBy: "Pope John XXII, 1323; Doctor of the Church: Pope Pius V, 1567",
    tags: ["Doctor of the Church", "Dominican", "Philosopher", "Theologian", "Scholar"],
  },
  {
    name: "Saint John Bosco",
    month: 1, day: 31,
    feastDate: "January 31",
    feastType: "Memorial",
    liturgicalColor: "White",
    shortBio: "Italian priest who dedicated his life to the education and care of poor youth in Turin. Founder of the Salesians of Don Bosco. He used a 'preventive system' of education based on reason, religion, and loving kindness.",
    bornYear: "1815",
    diedYear: "1888",
    patronOf: "youth, editors, publishers, schoolchildren, apprentices",
    canonizedBy: "Pope Pius XI, 1934",
    tags: ["Priest", "Educator", "Founder", "Youth Ministry", "Italian"],
  },
  {
    name: "Saint Blase",
    month: 2, day: 3,
    feastDate: "February 3",
    feastType: "Optional Memorial",
    liturgicalColor: "Red",
    shortBio: "Bishop of Sebaste in Armenia and martyr under Emperor Licinius. The blessing of throats on his feast day commemorates his miraculous cure of a boy choking on a fishbone.",
    bornYear: "Unknown",
    diedYear: "316",
    patronOf: "those with throat ailments, wool workers",
    canonizedBy: "Pre-Congregation",
    tags: ["Martyr", "Bishop", "Early Church", "Healing"],
  },
  {
    name: "Saint Ansgar",
    month: 2, day: 3,
    feastDate: "February 3",
    feastType: "Optional Memorial",
    liturgicalColor: "White",
    shortBio: "Benedictine monk and 'Apostle of the North' who brought Christianity to Denmark and Sweden. Archbishop of Hamburg-Bremen, he faced constant persecution and setbacks but never abandoned his missionary work.",
    bornYear: "801",
    diedYear: "865",
    patronOf: "Scandinavia, Denmark, Germany",
    canonizedBy: "Pre-Congregation",
    tags: ["Missionary", "Archbishop", "Benedictine", "Scandinavia"],
  },
  {
    name: "Saint Agatha",
    month: 2, day: 5,
    feastDate: "February 5",
    feastType: "Memorial",
    liturgicalColor: "Red",
    shortBio: "Sicilian virgin and martyr who refused the advances of the Roman consul Quintianus. She suffered horrific tortures but was miraculously healed in prison by Saint Peter the Apostle before her final martyrdom.",
    bornYear: "c. 231",
    diedYear: "c. 251",
    patronOf: "breast cancer patients, nurses, bell founders, bakers, Sicily",
    canonizedBy: "Pre-Congregation",
    tags: ["Martyr", "Virgin", "Early Church", "Sicilian"],
  },
  {
    name: "Saint Paul Miki and Companions",
    month: 2, day: 6,
    feastDate: "February 6",
    feastType: "Memorial",
    liturgicalColor: "Red",
    shortBio: "Twenty-six martyrs crucified in Nagasaki, Japan, in 1597 under Toyotomi Hideyoshi. They included Franciscan missionaries, Jesuit brothers, and Japanese laypeople. Saint Paul Miki preached from his cross.",
    bornYear: "c. 1564",
    diedYear: "1597",
    patronOf: "Japan",
    canonizedBy: "Pope Pius IX, 1862",
    tags: ["Martyrs", "Japan", "Missionaries", "Jesuit", "Franciscan"],
  },
  {
    name: "Saint Jerome Emiliani",
    month: 2, day: 8,
    feastDate: "February 8",
    feastType: "Optional Memorial",
    liturgicalColor: "White",
    shortBio: "Venetian soldier who was imprisoned and experienced a conversion. He founded the Somaschi order to care for orphans, foundlings, the sick, and the poor. Patron saint of orphans and abandoned children.",
    bornYear: "1481",
    diedYear: "1537",
    patronOf: "orphans, abandoned children",
    canonizedBy: "Pope Clement XIII, 1767",
    tags: ["Priest", "Founder", "Social Welfare", "Orphans"],
  },
  {
    name: "Saint Josephine Bakhita",
    month: 2, day: 8,
    feastDate: "February 8",
    feastType: "Optional Memorial",
    liturgicalColor: "White",
    shortBio: "Sudanese-Italian Canossian sister. Kidnapped and enslaved as a child in Sudan, she eventually came to Italy, converted to Catholicism, and became a nun known for her joy, gentleness, and holiness.",
    bornYear: "c. 1869",
    diedYear: "1947",
    patronOf: "Sudan, South Sudan, trafficking victims",
    canonizedBy: "Pope John Paul II, 2000",
    tags: ["Slavery", "Convert", "African", "Religious Sister", "Sudan"],
  },
  {
    name: "Our Lady of Lourdes",
    month: 2, day: 11,
    feastDate: "February 11",
    feastType: "Optional Memorial",
    liturgicalColor: "White",
    shortBio: "On this date in 1858, the Blessed Virgin Mary appeared for the first of eighteen times to Bernadette Soubirous in the grotto of Massabielle in Lourdes, France, identifying herself as 'the Immaculate Conception.'",
    bornYear: "",
    diedYear: "",
    patronOf: "the sick, France",
    tags: ["Marian Apparition", "Healing", "Pilgrimage", "France"],
  },
  {
    name: "Saints Cyril and Methodius",
    month: 2, day: 14,
    feastDate: "February 14",
    feastType: "Memorial",
    liturgicalColor: "White",
    shortBio: "Greek brothers and missionaries to the Slavic peoples. Cyril invented the Glagolitic alphabet (the precursor to Cyrillic) so the Slavs could have the Bible and liturgy in their own language. Co-Patron Saints of Europe.",
    bornYear: "c. 826 (Cyril), c. 815 (Methodius)",
    diedYear: "869 (Cyril), 885 (Methodius)",
    patronOf: "Europe, Moravia, ecumenism, translators",
    canonizedBy: "Pre-Congregation; declared Co-Patrons of Europe by Pope John Paul II, 1980",
    tags: ["Missionaries", "Slavic Peoples", "Alphabet", "Patron of Europe"],
  },
  {
    name: "Saint Peter Damian",
    month: 2, day: 21,
    feastDate: "February 21",
    feastType: "Optional Memorial",
    liturgicalColor: "White",
    shortBio: "Benedictine monk, Cardinal, and Doctor of the Church who worked tirelessly for ecclesiastical reform in the 11th century, combating simony and clerical corruption. A severe ascetic and eloquent writer.",
    bornYear: "c. 1007",
    diedYear: "1072",
    patronOf: "reformers",
    canonizedBy: "Doctor of the Church declared by Pope Leo XII, 1828",
    tags: ["Doctor of the Church", "Cardinal", "Reformer", "Benedictine"],
  },
  {
    name: "Chair of Saint Peter",
    month: 2, day: 22,
    feastDate: "February 22",
    feastType: "Feast",
    liturgicalColor: "White",
    shortBio: "This feast celebrates the authority given to Saint Peter as the first Bishop of Rome and head of the Apostles. The 'Chair' (cathedra) represents the teaching authority of the Pope as Peter's successor.",
    bornYear: "",
    diedYear: "",
    patronOf: "the Papacy",
    tags: ["Papacy", "Peter", "Teaching Authority", "Magisterium"],
  },
  {
    name: "Saint Polycarp",
    month: 2, day: 23,
    feastDate: "February 23",
    feastType: "Memorial",
    liturgicalColor: "Red",
    shortBio: "Bishop of Smyrna and disciple of Saint John the Apostle. Martyred at the age of 86, he refused to deny Christ, saying: 'Eighty-six years I have served Him, and He has done me no wrong. How then can I blaspheme my King and my Savior?'",
    bornYear: "c. 69",
    diedYear: "155",
    patronOf: "earache sufferers",
    canonizedBy: "Pre-Congregation",
    tags: ["Martyr", "Bishop", "Apostolic Father", "Early Church"],
  },
  {
    name: "Saint Katharine Drexel",
    month: 3, day: 3,
    feastDate: "March 3",
    feastType: "Optional Memorial (USA)",
    liturgicalColor: "White",
    shortBio: "Philadelphia heiress who used her entire inheritance to found the Sisters of the Blessed Sacrament and establish schools for Native Americans and African Americans. A champion of racial justice motivated by Eucharistic love.",
    bornYear: "1858",
    diedYear: "1955",
    patronOf: "philanthropists, racial justice, Native Americans",
    canonizedBy: "Pope John Paul II, 2000",
    tags: ["Foundress", "Social Justice", "Education", "American", "Racial Equality"],
  },
  {
    name: "Saint Frances of Rome",
    month: 3, day: 9,
    feastDate: "March 9",
    feastType: "Optional Memorial",
    liturgicalColor: "White",
    shortBio: "Roman noblewoman who balanced the duties of wife, mother, and mystic for 40 years before founding the Oblates of Tor de' Specchi after her husband's death. She is said to have had her guardian angel visible to her at all times.",
    bornYear: "1384",
    diedYear: "1440",
    patronOf: "motorists, widows, Benedictine oblates, Rome",
    canonizedBy: "Pope Paul V, 1608",
    tags: ["Mystic", "Wife", "Mother", "Foundress", "Italian"],
  },
  {
    name: "Saint Louise de Marillac",
    month: 3, day: 15,
    feastDate: "March 15",
    feastType: "Memorial",
    liturgicalColor: "White",
    shortBio: "Co-founder of the Daughters of Charity with Saint Vincent de Paul. A widowed noblewoman who organized women to serve the poor in hospitals, prisons, and homes. She transformed Catholic social work.",
    bornYear: "1591",
    diedYear: "1660",
    patronOf: "social workers, widows, people rejected by religious orders",
    canonizedBy: "Pope Pius XI, 1934",
    tags: ["Foundress", "Social Work", "Widow", "French"],
  },
  {
    name: "Saint Turibius of Mogrovejo",
    month: 3, day: 23,
    feastDate: "March 23",
    feastType: "Memorial",
    liturgicalColor: "White",
    shortBio: "Archbishop of Lima, Peru, and great evangelizer of South America. In his 25-year episcopate, he confirmed nearly 500,000 indigenous people, confirmed Saints Rose of Lima and Martin de Porres, and traveled 40,000 miles on horseback.",
    bornYear: "1538",
    diedYear: "1606",
    patronOf: "Latin America, Peru, bishops of Latin America",
    canonizedBy: "Pope Innocent XI, 1726",
    tags: ["Archbishop", "Missionary", "South America", "Peru"],
  },
  {
    name: "Saint Stanislaus",
    month: 4, day: 11,
    feastDate: "April 11",
    feastType: "Memorial",
    liturgicalColor: "Red",
    shortBio: "Bishop of Krakow and martyr. He was killed by King Boleslaus II of Poland for excommunicating the king due to his crimes and injustices. The patron saint of Poland and of moral order in society.",
    bornYear: "1030",
    diedYear: "1079",
    patronOf: "Poland, Krakow, moral order",
    canonizedBy: "Pope Innocent IV, 1253",
    tags: ["Martyr", "Bishop", "Poland", "Social Justice"],
  },
  {
    name: "Saint Anselm",
    month: 4, day: 21,
    feastDate: "April 21",
    feastType: "Memorial",
    liturgicalColor: "White",
    shortBio: "Archbishop of Canterbury and Doctor of the Church. Known as the 'Father of Scholasticism' for his method of faith seeking understanding (fides quaerens intellectum). Developed the ontological argument for God's existence.",
    bornYear: "c. 1033",
    diedYear: "1109",
    patronOf: "theologians",
    canonizedBy: "Pope Alexander VI; Doctor of the Church: Pope Clement XI, 1720",
    tags: ["Doctor of the Church", "Archbishop", "Scholasticism", "Theologian"],
  },
  {
    name: "Saint George",
    month: 4, day: 23,
    feastDate: "April 23",
    feastType: "Optional Memorial",
    liturgicalColor: "Red",
    shortBio: "Roman soldier and martyr of the early Church, venerated throughout the East and West. The legends of his slaying a dragon represent his victory over evil. Patron saint of England, Georgia, and soldiers.",
    bornYear: "c. 275",
    diedYear: "c. 303",
    patronOf: "England, Georgia, soldiers, cavalry, knights, archers",
    canonizedBy: "Pre-Congregation",
    tags: ["Martyr", "Soldier", "Roman", "England"],
  },
  {
    name: "Saint Adalbert",
    month: 4, day: 23,
    feastDate: "April 23",
    feastType: "Optional Memorial",
    liturgicalColor: "Red",
    shortBio: "Bishop of Prague and martyr who evangelized Prussia and Poland. A close friend of Emperor Otto III, he gave up his wealthy see to live as a monk and ultimately died as a martyr while preaching to the Prussians.",
    bornYear: "c. 956",
    diedYear: "997",
    patronOf: "Bohemia, Poland, Hungary",
    canonizedBy: "Pope Sylvester II, 999",
    tags: ["Martyr", "Bishop", "Missionary", "Czech", "Poland"],
  },
  {
    name: "Saint Catherine of Siena",
    month: 4, day: 29,
    feastDate: "April 29",
    feastType: "Memorial",
    liturgicalColor: "White",
    shortBio: "Dominican tertiary, mystic, Doctor of the Church, and Co-Patroness of Europe. Despite being illiterate, she dictated hundreds of letters to popes and rulers. Her dialogue with God (The Dialogue) is a masterpiece of mystical theology. She convinced Pope Gregory XI to return to Rome from Avignon.",
    bornYear: "1347",
    diedYear: "1380",
    patronOf: "Italy, Europe, nurses, fire prevention, people ridiculed for their faith",
    canonizedBy: "Pope Pius II, 1461; Doctor of the Church: Pope Paul VI, 1970",
    tags: ["Doctor of the Church", "Dominican", "Mystic", "Patron of Europe", "Italian"],
  },
  {
    name: "Saint Pius V",
    month: 4, day: 30,
    feastDate: "April 30",
    feastType: "Optional Memorial",
    liturgicalColor: "White",
    shortBio: "Dominican friar who became Pope during the Counter-Reformation. He implemented the decrees of the Council of Trent, excommunicated Queen Elizabeth I, standardized the Roman Rite Mass (Tridentine Mass), and organized the Holy League that defeated the Ottomans at the Battle of Lepanto.",
    bornYear: "1504",
    diedYear: "1572",
    patronOf: "the Church",
    canonizedBy: "Pope Clement XI, 1712",
    tags: ["Pope", "Dominican", "Counter-Reformation", "Tridentine Mass"],
  },
  {
    name: "Saint Athanasius",
    month: 5, day: 2,
    feastDate: "May 2",
    feastType: "Memorial",
    liturgicalColor: "White",
    shortBio: "Bishop of Alexandria and Doctor of the Church, called 'Athanasius contra mundum' (Athanasius against the world) for his lifelong, relentless defense of the divinity of Christ against Arianism. He was exiled five times but never recanted.",
    bornYear: "c. 296",
    diedYear: "373",
    patronOf: "theologians",
    canonizedBy: "Pre-Congregation; Doctor of the Church: Pope Pius V, 1568",
    tags: ["Doctor of the Church", "Bishop", "Anti-Arian", "Egyptian", "Theologian"],
  },
  {
    name: "Saints Philip and James",
    month: 5, day: 3,
    feastDate: "May 3",
    feastType: "Feast",
    liturgicalColor: "Red",
    shortBio: "Two of the Twelve Apostles. Philip, from Bethsaida, asked Jesus to 'show us the Father.' James the Less, brother of the Lord, was the first Bishop of Jerusalem and author of the Epistle of James.",
    bornYear: "1st century",
    diedYear: "1st century",
    patronOf: "Philip: Uruguay, hatters; James: pharmacists, fullers",
    canonizedBy: "Pre-Congregation",
    tags: ["Apostles", "Martyrs", "New Testament"],
  },
  {
    name: "Saint Matthias",
    month: 5, day: 14,
    feastDate: "May 14",
    feastType: "Feast",
    liturgicalColor: "Red",
    shortBio: "Chosen by lot to replace Judas Iscariot as one of the Twelve Apostles (Acts 1:15-26). He had been a follower of Jesus from the time of His baptism and witnessed the Resurrection.",
    bornYear: "1st century",
    diedYear: "c. 80 AD",
    patronOf: "alcoholics, tailors, carpenters, smallpox sufferers",
    canonizedBy: "Pre-Congregation",
    tags: ["Apostle", "Martyr", "New Testament"],
  },
  {
    name: "Saint John I",
    month: 5, day: 18,
    feastDate: "May 18",
    feastType: "Optional Memorial",
    liturgicalColor: "Red",
    shortBio: "Pope and martyr who was sent by Theodoric the Great to negotiate with Emperor Justin I on behalf of the Arian Goths. Despite his mission's success, Theodoric suspected betrayal and had the aging pope imprisoned, where he died.",
    bornYear: "Unknown",
    diedYear: "526",
    patronOf: "",
    canonizedBy: "Pre-Congregation",
    tags: ["Pope", "Martyr", "Early Church"],
  },
  {
    name: "Saint Bernardine of Siena",
    month: 5, day: 20,
    feastDate: "May 20",
    feastType: "Optional Memorial",
    liturgicalColor: "White",
    shortBio: "Franciscan friar and one of the greatest preachers of the 15th century. He popularized devotion to the Holy Name of Jesus and the IHS monogram. His brilliant oratory drew crowds of thousands throughout Italy.",
    bornYear: "1380",
    diedYear: "1444",
    patronOf: "advertisers, communications workers, gambling addicts, Italy",
    canonizedBy: "Pope Nicholas V, 1450",
    tags: ["Franciscan", "Preacher", "Holy Name of Jesus", "Italian"],
  },
  {
    name: "Saint Rita of Cascia",
    month: 5, day: 22,
    feastDate: "May 22",
    feastType: "Optional Memorial",
    liturgicalColor: "White",
    shortBio: "Italian Augustinian nun known as the 'Patron Saint of Impossible Causes.' She endured a difficult arranged marriage, the violent deaths of her husband and sons, and bore the stigmata of Christ's crown of thorns on her forehead.",
    bornYear: "1381",
    diedYear: "1457",
    patronOf: "impossible causes, desperate situations, wounds, abused wives and widows",
    canonizedBy: "Pope Leo XIII, 1900",
    tags: ["Augustinian", "Mystic", "Stigmatist", "Italian", "Widow"],
  },
  {
    name: "Saint Philip Neri",
    month: 5, day: 26,
    feastDate: "May 26",
    feastType: "Memorial",
    liturgicalColor: "White",
    shortBio: "Italian priest called the 'Apostle of Rome.' Known for his extraordinary joy, humor, and love of youth. He founded the Congregation of the Oratory and transformed Roman religious life through joyful, informal gatherings.",
    bornYear: "1515",
    diedYear: "1595",
    patronOf: "Rome, joy, youth workers, US Army Special Forces",
    canonizedBy: "Pope Gregory XV, 1622",
    tags: ["Priest", "Founder", "Joy", "Italian", "Counter-Reformation"],
  },
  {
    name: "Saint Augustine of Canterbury",
    month: 5, day: 27,
    feastDate: "May 27",
    feastType: "Feast",
    liturgicalColor: "White",
    shortBio: "Benedictine monk sent by Pope Gregory the Great to evangelize England in 597. He converted King Ethelbert of Kent and became the first Archbishop of Canterbury. Called the 'Apostle of the English.'",
    bornYear: "Unknown",
    diedYear: "604",
    patronOf: "England, the Church of England",
    canonizedBy: "Pre-Congregation",
    tags: ["Archbishop", "Benedictine", "Missionary", "England"],
  },
  {
    name: "Saint Joan of Arc",
    month: 5, day: 30,
    feastDate: "May 30",
    feastType: "Optional Memorial",
    liturgicalColor: "White",
    shortBio: "French peasant girl who, at age 17, led French armies to victory at Orléans during the Hundred Years' War, guided by visions of Saints Michael, Catherine, and Margaret. Captured, tried for heresy, and burned at the stake. Rehabilitated 25 years later.",
    bornYear: "c. 1412",
    diedYear: "1431",
    patronOf: "France, soldiers, prisoners, people ridiculed for their faith",
    canonizedBy: "Pope Benedict XV, 1920",
    tags: ["Martyr", "Mystic", "Soldier", "French", "National Hero"],
  },
  {
    name: "Saint Justin Martyr",
    month: 6, day: 1,
    feastDate: "June 1",
    feastType: "Memorial",
    liturgicalColor: "Red",
    shortBio: "Philosopher and first great Christian apologist who used Greek philosophy to explain and defend Christianity to pagans and the Roman Emperor. He wrote two Apologies and the Dialogue with Trypho before his martyrdom.",
    bornYear: "c. 100",
    diedYear: "c. 165",
    patronOf: "philosophers, apologists",
    canonizedBy: "Pre-Congregation",
    tags: ["Martyr", "Apologist", "Philosopher", "Early Church"],
  },
  {
    name: "Saints Marcellinus and Peter",
    month: 6, day: 2,
    feastDate: "June 2",
    feastType: "Optional Memorial",
    liturgicalColor: "Red",
    shortBio: "Roman priest and exorcist martyred under Diocletian around 304. Their names appear in the Roman Canon of the Mass. Pope Damasus learned about their martyrdom from the executioner who buried them.",
    bornYear: "Unknown",
    diedYear: "c. 304",
    patronOf: "",
    canonizedBy: "Pre-Congregation",
    tags: ["Martyrs", "Early Church", "Roman Canon"],
  },
];

export const seedSaints2 = mutation({
  args: {},
  handler: async (ctx) => {
    const existing = await ctx.db.query("saints").collect();
    const existingKeys = new Set(
      existing.map((s) => `${s.month}-${s.day}-${s.name.toLowerCase()}`)
    );

    let added = 0;
    for (const s of ADDITIONAL_SAINTS) {
      const key = `${s.month}-${s.day}-${s.name.toLowerCase()}`;
      if (existingKeys.has(key)) continue;

      const doy = dayOfYear(s.month, s.day);
      const fullBio = buildBio(s);

      await ctx.db.insert("saints", {
        name: s.name,
        month: s.month,
        day: s.day,
        dayOfYear: doy,
        feastDate: s.feastDate,
        shortBio: s.shortBio,
        fullBio,
        bornYear: s.bornYear || undefined,
        diedYear: s.diedYear || undefined,
        patronOf: s.patronOf || undefined,
        feastType: s.feastType || undefined,
        liturgicalColor: s.liturgicalColor || undefined,
        canonizedBy: s.canonizedBy || undefined,
        tags: s.tags,
        isActive: true,
      });
      added++;
    }

    return { added };
  },
});
