import { mutation } from "./_generated/server";

const NEW_VERSES = [
  // FROM BibleStudyTools (NIV)
  {
    book: "Jeremiah",
    chapter: 29,
    verse: 11,
    text: "For I know the plans I have for you, declares the Lord, plans for welfare and not for evil, to give you a future and a hope.",
    translation: "NIV",
    category: "Hope",
    tags: ["hope", "plans", "future", "God's will"],
  },
  {
    book: "Deuteronomy",
    chapter: 31,
    verse: 6,
    text: "Be strong and courageous. Do not fear or be in dread of them, for it is the Lord your God who goes with you.",
    translation: "NIV",
    category: "Courage",
    tags: ["courage", "strength", "fear", "God's presence"],
  },
  {
    book: "Lamentations",
    chapter: 3,
    verse: 22,
    verseEnd: 23,
    text: "The steadfast love of the Lord never ceases; his mercies never come to an end; they are new every morning.",
    translation: "NIV",
    category: "Mercy",
    tags: ["mercy", "love", "morning", "steadfast"],
  },
  {
    book: "Psalm",
    chapter: 34,
    verse: 8,
    text: "Oh, taste and see that the Lord is good! Blessed is the man who takes refuge in him!",
    translation: "NIV",
    category: "Trust",
    tags: ["trust", "refuge", "goodness", "blessing"],
  },
  {
    book: "Isaiah",
    chapter: 26,
    verse: 3,
    text: "You will keep in perfect peace those whose minds are steadfast, because they trust in you.",
    translation: "NIV",
    category: "Peace",
    tags: ["peace", "trust", "steadfast", "mind"],
  },
  {
    book: "Galatians",
    chapter: 3,
    verse: 26,
    text: "So in Christ Jesus you are all children of God through faith",
    translation: "NIV",
    category: "Faith",
    tags: ["faith", "children of God", "Christ", "identity"],
  },
  {
    book: "Psalm",
    chapter: 56,
    verse: 3,
    text: "When I am afraid, I put my trust in you.",
    translation: "NIV",
    category: "Trust",
    tags: ["trust", "fear", "faith"],
  },
  {
    book: "Romans",
    chapter: 15,
    verse: 13,
    text: "May the God of hope fill you with all joy and peace as you trust in him.",
    translation: "NIV",
    category: "Hope",
    tags: ["hope", "joy", "peace", "trust"],
  },
  {
    book: "Proverbs",
    chapter: 17,
    verse: 17,
    text: "A friend loves at all times, and a brother is born for a time of adversity.",
    translation: "NIV",
    category: "Virtue",
    tags: ["friendship", "love", "brotherhood", "adversity"],
  },
  {
    book: "1 Corinthians",
    chapter: 16,
    verse: 13,
    text: "Be on your guard; stand firm in the faith; be courageous; be strong.",
    translation: "NIV",
    category: "Courage",
    tags: ["courage", "strength", "faith", "vigilance"],
  },
  {
    book: "Deuteronomy",
    chapter: 6,
    verse: 6,
    text: "These commandments that I give you today are to be on your hearts.",
    translation: "NIV",
    category: "Scripture",
    tags: ["commandments", "heart", "law", "scripture"],
  },
  {
    book: "Isaiah",
    chapter: 12,
    verse: 2,
    text: "Surely God is my salvation; I will trust and not be afraid. The LORD is my strength.",
    translation: "NIV",
    category: "Trust",
    tags: ["salvation", "trust", "strength", "fear"],
  },
  {
    book: "Proverbs",
    chapter: 21,
    verse: 21,
    text: "Whoever pursues righteousness and love finds life, prosperity and honor.",
    translation: "NIV",
    category: "Virtue",
    tags: ["righteousness", "love", "life", "honor"],
  },
  {
    book: "Isaiah",
    chapter: 43,
    verse: 2,
    text: "When you pass through the waters, I will be with you; and when you pass through the rivers, they will not sweep over you.",
    translation: "NIV",
    category: "Providence",
    tags: ["providence", "protection", "God's presence", "trials"],
  },
  {
    book: "John",
    chapter: 16,
    verse: 33,
    text: "In this world you will have trouble. But take heart! I have overcome the world.",
    translation: "NIV",
    category: "Hope",
    tags: ["hope", "victory", "world", "trouble"],
  },
  {
    book: "Mark",
    chapter: 10,
    verse: 27,
    text: "With man this is impossible, but not with God; all things are possible with God.",
    translation: "NIV",
    category: "Faith",
    tags: ["faith", "possibility", "God's power", "miracles"],
  },
  {
    book: "Matthew",
    chapter: 11,
    verse: 28,
    text: "Come to me, all you who are weary and burdened, and I will give you rest.",
    translation: "NIV",
    category: "Prayer",
    tags: ["rest", "weary", "invitation", "comfort"],
  },
  {
    book: "Matthew",
    chapter: 17,
    verse: 20,
    text: "If you have faith as small as a mustard seed, you can say to this mountain, 'Move from here to there,' and it will move.",
    translation: "NIV",
    category: "Faith",
    tags: ["faith", "mustard seed", "mountains", "miracles"],
  },
  {
    book: "Joshua",
    chapter: 1,
    verse: 9,
    text: "Have I not commanded you? Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you.",
    translation: "NIV",
    category: "Courage",
    tags: ["courage", "strength", "fear", "God's presence"],
  },
  {
    book: "Romans",
    chapter: 8,
    verse: 31,
    text: "If God is for us, who can be against us?",
    translation: "NIV",
    category: "Trust",
    tags: ["trust", "God's protection", "confidence", "faith"],
  },
  {
    book: "Psalm",
    chapter: 31,
    verse: 24,
    text: "Be strong and take heart, all you who hope in the LORD.",
    translation: "NIV",
    category: "Hope",
    tags: ["hope", "strength", "courage", "LORD"],
  },
  {
    book: "1 Thessalonians",
    chapter: 5,
    verse: 11,
    text: "Therefore encourage one another and build each other up.",
    translation: "NIV",
    category: "Virtue",
    tags: ["encouragement", "community", "building up", "virtue"],
  },
  {
    book: "Psalm",
    chapter: 107,
    verse: 1,
    text: "Give thanks to the LORD, for he is good; his love endures forever.",
    translation: "NIV",
    category: "Praise",
    tags: ["praise", "thanksgiving", "love", "goodness"],
  },
  {
    book: "Psalm",
    chapter: 27,
    verse: 4,
    text: "One thing I ask from the LORD, this only do I seek: that I may dwell in the house of the LORD all the days of my life.",
    translation: "NIV",
    category: "Prayer",
    tags: ["prayer", "dwelling", "seeking", "LORD's house"],
  },
  {
    book: "Psalm",
    chapter: 18,
    verse: 1,
    text: "I love you, LORD, my strength. The LORD is my rock, my fortress and my deliverer.",
    translation: "NIV",
    category: "Praise",
    tags: ["praise", "love", "strength", "rock", "fortress"],
  },
  {
    book: "2 Corinthians",
    chapter: 1,
    verse: 3,
    text: "Praise be to the God and Father of our Lord Jesus Christ, the Father of compassion and the God of all comfort.",
    translation: "NIV",
    category: "Praise",
    tags: ["praise", "comfort", "compassion", "God the Father"],
  },
  {
    book: "John",
    chapter: 11,
    verse: 25,
    text: "I am the resurrection and the life. The one who believes in me will live, even though they die.",
    translation: "NIV",
    category: "Resurrection",
    tags: ["resurrection", "life", "belief", "eternal life"],
  },
  {
    book: "Romans",
    chapter: 12,
    verse: 12,
    text: "Be joyful in hope, patient in affliction, faithful in prayer.",
    translation: "NIV",
    category: "Prayer",
    tags: ["prayer", "hope", "patience", "joy"],
  },
  {
    book: "Psalm",
    chapter: 143,
    verse: 8,
    text: "Let the morning bring me word of your unfailing love, for I have put my trust in you.",
    translation: "NIV",
    category: "Trust",
    tags: ["trust", "love", "morning", "unfailing"],
  },
  {
    book: "Psalm",
    chapter: 73,
    verse: 26,
    text: "My flesh and my heart may fail, but God is the strength of my heart and my portion forever.",
    translation: "NIV",
    category: "Trust",
    tags: ["trust", "strength", "heart", "God's provision"],
  },
  {
    book: "Psalm",
    chapter: 121,
    verse: 7,
    text: "The LORD will keep you from all harm; he will watch over your life.",
    translation: "NIV",
    category: "Providence",
    tags: ["providence", "protection", "watching over", "safety"],
  },
  {
    book: "Numbers",
    chapter: 6,
    verse: 24,
    text: "The LORD bless you and keep you; the LORD make his face shine on you and be gracious to you.",
    translation: "NIV",
    category: "Blessing",
    tags: ["blessing", "grace", "protection", "Aaronic blessing"],
  },
  {
    book: "1 John",
    chapter: 4,
    verse: 16,
    text: "And so we know and rely on the love God has for us. God is love.",
    translation: "NIV",
    category: "Love",
    tags: ["love", "God is love", "reliance", "faith"],
  },
  {
    book: "2 Corinthians",
    chapter: 3,
    verse: 17,
    text: "Now the Lord is the Spirit, and where the Spirit of the Lord is, there is freedom.",
    translation: "NIV",
    category: "Holy Spirit",
    tags: ["Holy Spirit", "freedom", "Lord", "Spirit"],
  },
  {
    book: "Ephesians",
    chapter: 4,
    verse: 32,
    text: "Be kind and compassionate to one another, forgiving each other, just as in Christ God forgave you.",
    translation: "NIV",
    category: "Virtue",
    tags: ["kindness", "compassion", "forgiveness", "virtue"],
  },
  {
    book: "1 Corinthians",
    chapter: 13,
    verse: 12,
    text: "For now we see only a reflection as in a mirror; then we shall see face to face.",
    translation: "NIV",
    category: "Heaven",
    tags: ["heaven", "vision", "eternity", "knowledge"],
  },
  // FROM Kendra Fletcher (NKJV)
  {
    book: "Leviticus",
    chapter: 19,
    verse: 11,
    text: "You shall not steal, nor deal falsely, nor lie to one another.",
    translation: "NKJV",
    category: "Commandments",
    tags: ["commandments", "honesty", "stealing", "lying"],
  },
  {
    book: "Numbers",
    chapter: 23,
    verse: 19,
    text: "God is not a man, that He should lie, nor a son of man, that He should repent. Has He said, and will He not do? Or has He spoken, and will He not make it good?",
    translation: "NKJV",
    category: "Trust",
    tags: ["trust", "God's faithfulness", "truth", "promises"],
  },
  {
    book: "Joshua",
    chapter: 1,
    verse: 8,
    text: "This Book of the Law shall not depart from your mouth, but you shall meditate in it day and night, that you may observe to do according to all that is written in it.",
    translation: "NKJV",
    category: "Scripture",
    tags: ["scripture", "meditation", "law", "obedience"],
  },
  {
    book: "Psalm",
    chapter: 96,
    verse: 2,
    text: "Sing to the LORD, bless His name; proclaim the good news of His salvation from day to day.",
    translation: "NKJV",
    category: "Praise",
    tags: ["praise", "singing", "salvation", "proclamation"],
  },
  {
    book: "Psalm",
    chapter: 100,
    verse: 1,
    text: "Make a joyful shout to the LORD, all you lands! Serve the LORD with gladness; come before His presence with singing.",
    translation: "NKJV",
    category: "Praise",
    tags: ["praise", "joy", "singing", "worship"],
  },
  {
    book: "Psalm",
    chapter: 119,
    verse: 9,
    text: "How can a young man cleanse his way? By taking heed according to Your word.",
    translation: "NKJV",
    category: "Scripture",
    tags: ["scripture", "purity", "youth", "word of God"],
  },
  {
    book: "Psalm",
    chapter: 119,
    verse: 11,
    text: "Your word I have hidden in my heart, that I might not sin against You.",
    translation: "NKJV",
    category: "Scripture",
    tags: ["scripture", "heart", "sin", "word of God"],
  },
  {
    book: "Psalm",
    chapter: 147,
    verse: 5,
    text: "Great is our Lord, and mighty in power; His understanding is infinite.",
    translation: "NKJV",
    category: "Praise",
    tags: ["praise", "power", "greatness", "understanding"],
  },
  {
    book: "Proverbs",
    chapter: 3,
    verse: 9,
    text: "Honor the LORD with your possessions, and with the firstfruits of all your increase.",
    translation: "NKJV",
    category: "Virtue",
    tags: ["virtue", "honor", "firstfruits", "stewardship"],
  },
  {
    book: "Isaiah",
    chapter: 53,
    verse: 6,
    text: "All we like sheep have gone astray; we have turned, every one, to his own way; and the LORD has laid on Him the iniquity of us all.",
    translation: "NKJV",
    category: "Redemption",
    tags: ["redemption", "sin", "atonement", "suffering servant"],
  },
  {
    book: "Matthew",
    chapter: 1,
    verse: 21,
    text: "And she will bring forth a Son, and you shall call His name Jesus, for He will save His people from their sins.",
    translation: "NKJV",
    category: "Incarnation",
    tags: ["incarnation", "Jesus", "salvation", "sin"],
  },
  {
    book: "Matthew",
    chapter: 4,
    verse: 19,
    text: "Then He said to them, 'Follow Me, and I will make you fishers of men.'",
    translation: "NKJV",
    category: "Discipleship",
    tags: ["discipleship", "following Jesus", "mission", "fishers of men"],
  },
  {
    book: "Matthew",
    chapter: 5,
    verse: 16,
    text: "Let your light so shine before men, that they may see your good works and glorify your Father in heaven.",
    translation: "NKJV",
    category: "Discipleship",
    tags: ["discipleship", "light", "good works", "witness"],
  },
  {
    book: "Matthew",
    chapter: 6,
    verse: 33,
    text: "But seek first the kingdom of God and His righteousness, and all these things shall be added to you.",
    translation: "NKJV",
    category: "Trust",
    tags: ["trust", "kingdom of God", "righteousness", "seeking"],
  },
  {
    book: "Matthew",
    chapter: 7,
    verse: 13,
    text: "Enter by the narrow gate; for wide is the gate and broad is the way that leads to destruction, and there are many who go in by it.",
    translation: "NKJV",
    category: "Salvation",
    tags: ["salvation", "narrow gate", "way", "destruction"],
  },
  {
    book: "Matthew",
    chapter: 12,
    verse: 30,
    text: "He who is not with Me is against Me, and he who does not gather with Me scatters abroad.",
    translation: "NKJV",
    category: "Discipleship",
    tags: ["discipleship", "commitment", "gathering", "scattering"],
  },
  {
    book: "Matthew",
    chapter: 16,
    verse: 24,
    text: "If anyone desires to come after Me, let him deny himself, and take up his cross, and follow Me.",
    translation: "NKJV",
    category: "Discipleship",
    tags: ["discipleship", "cross", "self-denial", "following Jesus"],
  },
  {
    book: "Matthew",
    chapter: 18,
    verse: 20,
    text: "For where two or three are gathered together in My name, I am there in the midst of them.",
    translation: "NKJV",
    category: "Prayer",
    tags: ["prayer", "community", "gathering", "presence of God"],
  },
  {
    book: "Mark",
    chapter: 10,
    verse: 45,
    text: "For even the Son of Man did not come to be served, but to serve, and to give His life a ransom for many.",
    translation: "NKJV",
    category: "Redemption",
    tags: ["redemption", "service", "ransom", "Son of Man"],
  },
  {
    book: "Mark",
    chapter: 12,
    verse: 30,
    text: "And you shall love the LORD your God with all your heart, with all your soul, with all your mind, and with all your strength.",
    translation: "NKJV",
    category: "Love",
    tags: ["love", "commandment", "whole heart", "God"],
  },
  {
    book: "Luke",
    chapter: 6,
    verse: 35,
    text: "But love your enemies, do good, and lend, hoping for nothing in return; and your reward will be great.",
    translation: "NKJV",
    category: "Love",
    tags: ["love", "enemies", "generosity", "reward"],
  },
  {
    book: "Luke",
    chapter: 9,
    verse: 23,
    text: "Then He said to them all, 'If anyone desires to come after Me, let him deny himself, and take up his cross daily, and follow Me.'",
    translation: "NKJV",
    category: "Discipleship",
    tags: ["discipleship", "cross", "daily", "self-denial"],
  },
  {
    book: "Luke",
    chapter: 16,
    verse: 10,
    text: "He who is faithful in what is least is faithful also in much; and he who is unjust in what is least is unjust also in much.",
    translation: "NKJV",
    category: "Virtue",
    tags: ["virtue", "faithfulness", "stewardship", "integrity"],
  },
  {
    book: "John",
    chapter: 1,
    verse: 1,
    text: "In the beginning was the Word, and the Word was with God, and the Word was God.",
    translation: "NKJV",
    category: "Incarnation",
    tags: ["incarnation", "Word", "beginning", "God"],
  },
  {
    book: "John",
    chapter: 1,
    verse: 12,
    text: "But as many as received Him, to them He gave the right to become children of God, to those who believe in His name.",
    translation: "NKJV",
    category: "Salvation",
    tags: ["salvation", "children of God", "belief", "receiving Christ"],
  },
  {
    book: "John",
    chapter: 3,
    verse: 36,
    text: "He who believes in the Son has everlasting life; and he who does not believe the Son shall not see life.",
    translation: "NKJV",
    category: "Salvation",
    tags: ["salvation", "eternal life", "belief", "Son of God"],
  },
  {
    book: "John",
    chapter: 5,
    verse: 24,
    text: "Most assuredly, I say to you, he who hears My word and believes in Him who sent Me has everlasting life.",
    translation: "NKJV",
    category: "Salvation",
    tags: ["salvation", "eternal life", "hearing", "belief"],
  },
  {
    book: "John",
    chapter: 13,
    verse: 34,
    text: "A new commandment I give to you, that you love one another; as I have loved you, that you also love one another.",
    translation: "NKJV",
    category: "Love",
    tags: ["love", "commandment", "one another", "new commandment"],
  },
  {
    book: "John",
    chapter: 14,
    verse: 21,
    text: "He who has My commandments and keeps them, it is he who loves Me.",
    translation: "NKJV",
    category: "Love",
    tags: ["love", "commandments", "obedience", "relationship"],
  },
  {
    book: "John",
    chapter: 15,
    verse: 7,
    text: "If you abide in Me, and My words abide in you, you will ask what you desire, and it shall be done for you.",
    translation: "NKJV",
    category: "Prayer",
    tags: ["prayer", "abiding", "words", "answered prayer"],
  },
  {
    book: "John",
    chapter: 17,
    verse: 17,
    text: "Sanctify them by Your truth. Your word is truth.",
    translation: "NKJV",
    category: "Scripture",
    tags: ["scripture", "truth", "sanctification", "word of God"],
  },
  {
    book: "John",
    chapter: 20,
    verse: 31,
    text: "but these are written that you may believe that Jesus is the Christ, the Son of God, and that believing you may have life in His name.",
    translation: "NKJV",
    category: "Faith",
    tags: ["faith", "belief", "Christ", "life"],
  },
  {
    book: "Acts",
    chapter: 1,
    verse: 8,
    text: "But you shall receive power when the Holy Spirit has come upon you; and you shall be witnesses to Me in Jerusalem, and in all Judea and Samaria, and to the end of the earth.",
    translation: "NKJV",
    category: "Holy Spirit",
    tags: ["Holy Spirit", "power", "witness", "mission"],
  },
  {
    book: "Acts",
    chapter: 4,
    verse: 12,
    text: "Nor is there salvation in any other, for there is no other name under heaven given among men by which we must be saved.",
    translation: "NKJV",
    category: "Salvation",
    tags: ["salvation", "Jesus", "name", "exclusivity"],
  },
  {
    book: "Romans",
    chapter: 1,
    verse: 16,
    text: "For I am not ashamed of the gospel of Christ, for it is the power of God to salvation for everyone who believes.",
    translation: "NKJV",
    category: "Faith",
    tags: ["faith", "gospel", "salvation", "power of God"],
  },
  {
    book: "Romans",
    chapter: 3,
    verse: 23,
    text: "for all have sinned and fall short of the glory of God",
    translation: "NKJV",
    category: "Sin",
    tags: ["sin", "glory of God", "universal sin", "fallen nature"],
  },
  {
    book: "Romans",
    chapter: 5,
    verse: 8,
    text: "But God demonstrates His own love toward us, in that while we were still sinners, Christ died for us.",
    translation: "NKJV",
    category: "Redemption",
    tags: ["redemption", "love", "Christ's death", "sinners"],
  },
  {
    book: "Romans",
    chapter: 6,
    verse: 23,
    text: "For the wages of sin is death, but the gift of God is eternal life in Christ Jesus our Lord.",
    translation: "NKJV",
    category: "Salvation",
    tags: ["salvation", "sin", "death", "eternal life"],
  },
  {
    book: "Romans",
    chapter: 8,
    verse: 1,
    text: "There is therefore now no condemnation to those who are in Christ Jesus.",
    translation: "NKJV",
    category: "Salvation",
    tags: ["salvation", "condemnation", "Christ Jesus", "freedom"],
  },
  {
    book: "Romans",
    chapter: 10,
    verse: 9,
    text: "that if you confess with your mouth the Lord Jesus and believe in your heart that God has raised Him from the dead, you will be saved.",
    translation: "NKJV",
    category: "Salvation",
    tags: ["salvation", "confession", "belief", "resurrection"],
  },
  {
    book: "Romans",
    chapter: 10,
    verse: 17,
    text: "So then faith comes by hearing, and hearing by the word of God.",
    translation: "NKJV",
    category: "Faith",
    tags: ["faith", "hearing", "word of God", "belief"],
  },
  {
    book: "Galatians",
    chapter: 2,
    verse: 20,
    text: "I have been crucified with Christ; it is no longer I who live, but Christ lives in me; and the life which I now live in the flesh I live by faith in the Son of God.",
    translation: "NKJV",
    category: "Discipleship",
    tags: ["discipleship", "crucified with Christ", "faith", "new life"],
  },
  {
    book: "Galatians",
    chapter: 6,
    verse: 7,
    text: "Do not be deceived, God is not mocked; for whatever a man sows, that he will also reap.",
    translation: "NKJV",
    category: "Virtue",
    tags: ["virtue", "sowing and reaping", "consequences", "God's justice"],
  },
  {
    book: "Ephesians",
    chapter: 1,
    verse: 7,
    text: "In Him we have redemption through His blood, the forgiveness of sins, according to the riches of His grace.",
    translation: "NKJV",
    category: "Redemption",
    tags: ["redemption", "blood of Christ", "forgiveness", "grace"],
  },
  {
    book: "Philippians",
    chapter: 1,
    verse: 21,
    text: "For to me, to live is Christ, and to die is gain.",
    translation: "NKJV",
    category: "Discipleship",
    tags: ["discipleship", "Christ", "life", "death"],
  },
  {
    book: "Philippians",
    chapter: 2,
    verse: 3,
    text: "Let nothing be done through selfish ambition or conceit, but in lowliness of mind let each esteem others better than himself.",
    translation: "NKJV",
    category: "Virtue",
    tags: ["virtue", "humility", "others-focused", "selflessness"],
  },
  {
    book: "Philippians",
    chapter: 3,
    verse: 20,
    text: "For our citizenship is in heaven, from which we also eagerly wait for the Savior, the Lord Jesus Christ.",
    translation: "NKJV",
    category: "Heaven",
    tags: ["heaven", "citizenship", "waiting", "Savior"],
  },
  {
    book: "Colossians",
    chapter: 3,
    verse: 16,
    text: "Let the word of Christ dwell in you richly in all wisdom, teaching and admonishing one another in psalms and hymns and spiritual songs.",
    translation: "NKJV",
    category: "Scripture",
    tags: ["scripture", "word of Christ", "worship", "community"],
  },
  {
    book: "Colossians",
    chapter: 4,
    verse: 2,
    text: "Continue earnestly in prayer, being vigilant in it with thanksgiving.",
    translation: "NKJV",
    category: "Prayer",
    tags: ["prayer", "thanksgiving", "vigilance", "perseverance"],
  },
  {
    book: "1 Thessalonians",
    chapter: 5,
    verse: 16,
    verseEnd: 18,
    text: "Rejoice always, pray without ceasing, in everything give thanks; for this is the will of God in Christ Jesus for you.",
    translation: "NKJV",
    category: "Prayer",
    tags: ["prayer", "rejoicing", "thanksgiving", "God's will"],
  },
  {
    book: "1 Timothy",
    chapter: 2,
    verse: 5,
    text: "For there is one God and one Mediator between God and men, the Man Christ Jesus.",
    translation: "NKJV",
    category: "Creed",
    tags: ["creed", "one God", "mediator", "Christ Jesus"],
  },
  {
    book: "2 Timothy",
    chapter: 3,
    verse: 16,
    verseEnd: 17,
    text: "All Scripture is given by inspiration of God, and is profitable for doctrine, for reproof, for correction, for instruction in righteousness.",
    translation: "NKJV",
    category: "Scripture",
    tags: ["scripture", "inspiration", "doctrine", "righteousness"],
  },
  {
    book: "Hebrews",
    chapter: 2,
    verse: 18,
    text: "For in that He Himself has suffered, being tempted, He is able to aid those who are tempted.",
    translation: "NKJV",
    category: "Trust",
    tags: ["trust", "temptation", "suffering", "Christ's help"],
  },
  {
    book: "Hebrews",
    chapter: 4,
    verse: 12,
    text: "For the word of God is living and powerful, and sharper than any two-edged sword.",
    translation: "NKJV",
    category: "Scripture",
    tags: ["scripture", "word of God", "living", "powerful"],
  },
  {
    book: "Hebrews",
    chapter: 4,
    verse: 16,
    text: "Let us therefore come boldly to the throne of grace, that we may obtain mercy and find grace to help in time of need.",
    translation: "NKJV",
    category: "Prayer",
    tags: ["prayer", "throne of grace", "mercy", "boldness"],
  },
  {
    book: "Hebrews",
    chapter: 9,
    verse: 27,
    text: "And as it is appointed for men to die once, but after this the judgment.",
    translation: "NKJV",
    category: "Four Last Things",
    tags: ["four last things", "death", "judgment", "eternity"],
  },
  {
    book: "Hebrews",
    chapter: 10,
    verse: 24,
    verseEnd: 25,
    text: "And let us consider one another in order to stir up love and good works.",
    translation: "NKJV",
    category: "Virtue",
    tags: ["virtue", "community", "love", "good works"],
  },
  {
    book: "Hebrews",
    chapter: 13,
    verse: 5,
    text: "Let your conduct be without covetousness; be content with such things as you have. For He Himself has said, 'I will never leave you nor forsake you.'",
    translation: "NKJV",
    category: "Trust",
    tags: ["trust", "contentment", "covetousness", "God's presence"],
  },
  {
    book: "James",
    chapter: 1,
    verse: 2,
    verseEnd: 4,
    text: "My brethren, count it all joy when you fall into various trials, knowing that the testing of your faith produces patience.",
    translation: "NKJV",
    category: "Virtue",
    tags: ["virtue", "trials", "joy", "patience"],
  },
  {
    book: "James",
    chapter: 1,
    verse: 22,
    text: "But be doers of the word, and not hearers only, deceiving yourselves.",
    translation: "NKJV",
    category: "Scripture",
    tags: ["scripture", "doers", "hearers", "obedience"],
  },
  {
    book: "James",
    chapter: 2,
    verse: 10,
    text: "For whoever shall keep the whole law, and yet stumble in one point, he is guilty of all.",
    translation: "NKJV",
    category: "Morals",
    tags: ["morals", "law", "guilt", "obedience"],
  },
  {
    book: "1 John",
    chapter: 1,
    verse: 9,
    text: "If we confess our sins, He is faithful and just to forgive us our sins and to cleanse us from all unrighteousness.",
    translation: "NKJV",
    category: "Reconciliation",
    tags: ["reconciliation", "confession", "forgiveness", "cleansing"],
  },
  {
    book: "1 John",
    chapter: 3,
    verse: 18,
    text: "My little children, let us not love in word or in tongue, but in deed and in truth.",
    translation: "NKJV",
    category: "Love",
    tags: ["love", "action", "truth", "deeds"],
  },
  {
    book: "Revelation",
    chapter: 3,
    verse: 20,
    text: "Behold, I stand at the door and knock. If anyone hears My voice and opens the door, I will come in to him and dine with him, and he with Me.",
    translation: "NKJV",
    category: "Prayer",
    tags: ["prayer", "invitation", "door", "fellowship"],
  },
];

export const seedVerses2 = mutation({
  args: {},
  handler: async (ctx) => {
    const existing = await ctx.db.query("verses").collect();
    const existingKeys = new Set(
      existing.map((v) => `${v.book}-${v.chapter}-${v.verse}`)
    );
    let added = 0;
    for (const v of NEW_VERSES) {
      const key = `${v.book}-${v.chapter}-${v.verse}`;
      if (!existingKeys.has(key)) {
        await ctx.db.insert("verses", { ...v, isActive: true });
        added++;
      }
    }
    return { added };
  },
});
